// ISC-051 — the kingdom's item rows are the codex's: generated by tools/mk-items.mjs
// from content/hbt-content.json and content/gen/tier3-combinations.json; every kit
// item, shelf item and reward resolves to a row; no row is hand-typed.
// GEAR-DESIGN.md §1–§4 · CLAUDE.md "Never hand-edit generated/"
import { afterEach, describe, it, expect } from 'vitest'
import { readFileSync, existsSync, mkdtempSync, rmSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { ITEMS, itemOf } from '../src/content/items.js'
import { REWARDS } from '../src/content/rewards.js'
import { HERO_POOL, CIVILIANS } from '../src/content/heroes.js'
import { HERO_KITS, HERO_ITEM_SLOTS } from '../src/content/generated/kits.js'

const codex = JSON.parse(readFileSync('../content/hbt-content.json', 'utf8'))
const combos = JSON.parse(readFileSync('../content/gen/tier3-combinations.json', 'utf8')) as { id: string; base: string; enchant: string }[]
const outputs = ['items.ts', 'items-gaps.json', 'kits.ts', 'kits-gaps.json']
const temporary: string[] = []
const candidateDirectory = () => {
  const dir = mkdtempSync(join(tmpdir(), 'kingdom-isc-051-'))
  temporary.push(dir)
  return dir
}
afterEach(() => { for (const dir of temporary.splice(0)) rmSync(dir, { recursive: true, force: true }) })

describe('ISC-051 — the item rows are the codex\'s, generated', () => {
  it('the generated file exists, says so, and regenerating it changes nothing', () => {
    expect(existsSync('src/content/generated/items.ts')).toBe(true)
    const before = readFileSync('src/content/generated/items.ts', 'utf8')
    expect(before).toMatch(/GENERATED by tools\/mk-items\.mjs/)
    // V2 migration 2026-09-11: checking drift must not rewrite the evidence.
    // Every published artifact remains checked, now against isolated candidates.
    const out = candidateDirectory()
    const published = outputs.map((name) => readFileSync(join('src/content/generated', name), 'utf8'))
    execFileSync(process.execPath, ['tools/mk-items.mjs', '--out-dir', out], { stdio: 'pipe' })
    for (const [i, name] of outputs.entries()) {
      expect(readFileSync(join('src/content/generated', name), 'utf8'), `${name}: live output changed`).toBe(published[i])
      expect(readFileSync(join(out, name), 'utf8'), `${name}: generated content has drifted`).toBe(published[i])
    }
  })
  it('every codex item is a row with class, tier, hands, slots, restriction, sets, uses and cost', () => {
    for (const c of codex.items as { id: string; itemClass: string; tier: string | number }[]) {
      const r = itemOf(c.id)
      expect(r.itemClass).toBe(c.itemClass)
      expect(r.tier).toBe(Number(c.tier))
      expect(typeof r.hands).toBe('number'); expect(typeof r.slots).toBe('number')
      expect(Array.isArray(r.sets)).toBe(true)
      expect(r.uses === null || typeof r.uses === 'number').toBe(true)
      expect(typeof r.equipCost).toBe('object')
    }
    expect(ITEMS.length).toBeGreaterThan((codex.items as unknown[]).length)
  })
  it('every kit item on every pool hero and civilian resolves', () => {
    const kits = codex.kits.heroKits as Record<string, string[] | { pinned: string[] } | null>
    for (const h of [...HERO_POOL, ...CIVILIANS]) {
      const kit = kits[h.id]
      const items = Array.isArray(kit) ? kit : kit?.pinned ?? []
      for (const id of items) expect(() => itemOf(id), `${h.id} → ${id}`).not.toThrow()
    }
  })
  it('publishes every authored full kit and item-slot count, including units beyond the current draft pool', () => {
    // Current flat content owns these rows even while the kingdom draft pool
    // and engine catalogue are smaller. Publishing a kit does not field a unit.
    const heroes = codex.heroes.heroes as { id: string; kit: string[] | { pinned: string[] } | null; ported?: { itemSlots?: number } }[]
    expect(HERO_KITS).toEqual(Object.fromEntries(heroes.filter((h) => Array.isArray(h.kit)).map((h) => [h.id, h.kit])))
    expect(HERO_ITEM_SLOTS).toEqual(Object.fromEntries(heroes.filter((h) => Number.isInteger(h.ported?.itemSlots)).map((h) => [h.id, h.ported!.itemSlots])))
  })
  it('every combination is a tier-3 row carrying its base and enchant, or a NAMED gap on an enchant the codex lacks; the reward pool is a filter over the rows', () => {
    const gaps = JSON.parse(readFileSync('src/content/generated/items-gaps.json', 'utf8')) as { count: number; gaps: { id: string; needs: string }[] }
    const codexEnchants = new Set((codex.enchants as { id: string }[]).map((e) => e.id))
    let emitted = 0
    for (const c of combos) {
      const gap = gaps.gaps.find((g) => g.id === c.id)
      if (gap) { expect(codexEnchants.has(gap.needs)).toBe(false); expect(gap.needs).toBe(c.enchant); continue }
      const r = itemOf(c.id)
      expect(r.tier).toBe(3); expect(r.base).toBe(c.base); expect(r.enchant).toBe(c.enchant)
      expect(r.itemClass).toBe(itemOf(c.base).itemClass)
      emitted++
    }
    expect(emitted + gaps.count).toBe(combos.length)
    expect(emitted).toBeGreaterThan(100)
    for (const r of REWARDS) expect(itemOf(r.id).name).toBe(r.name)
    const src = readFileSync('src/content/rewards.ts', 'utf8')
    expect(src).not.toMatch(/\{\s*id:\s*'item\./)                           // no hand-typed rows
  })
  it('the tool refuses a combination whose base or enchant the codex does not have (Law 9)', () => {
    let out = ''
    try { execFileSync(process.execPath, ['tools/mk-items.mjs', '--combos', 'test/fixtures/bad-combos.json', '--out-dir', candidateDirectory()], { stdio: 'pipe', encoding: 'utf8' }) }
    catch (e) { out = String((e as { stderr?: string }).stderr ?? '') + String((e as { stdout?: string }).stdout ?? '') }
    expect(out).toMatch(/item\.no-such-base/)
  })
})
