// viewer.timed-effect-status-marks (engine backlog; found by the engine worker landing capability.effect-lasts-activations,
// 2026-10-05 — ruled 2026-10-04, engine DECISIONS.md 'his 28 reward weapons read back …': an effect that lasts a number of
// Activations; viewer SWITCHES.md lentStatusShownAsAStatus: "the three new statuses have no entry in src/theme.js STYLE, so
// they wear the fallback style — a green dot, which is Poison's hue").
// Display only: no engine change. This file holds what the marks and their words stand on — the engine's own rows and lines:
// each of the three powers (the Fire Gauntlet's Stoke, the Staff of the Ultimate Destroyer's Perfect Sight, Poison Coating)
// puts a status on its user whose row LENDS something and says what counts it down; the lines are the ordinary status lines
// (status.applied 3, status.reduced to 2, to 1, to 0, status.expired — or, for the coating, 1 for the rest of the Battle); the
// viewer's dump carries each row's `lends` and `countsDown` as the engine has them — and makes the fixture the page test
// plays: tools/fixtures/timed-effects.json, three Fire Mages each carrying one of the three items at the Orphanage, each
// using its power in its first Activation and then passing four more — fielded by createBattle and moved by the engine's own
// functions (usePower, beginActivation, endActivation, endOfActivation), as the engine's own test of the capability does.
// The viewer's half is ../viewer/tools/timed-effect-status-marks.test.mjs.
//
//   TIMED_WRITE=1 npm test -- viewer.timed-effect-status-marks     rewrites the fixture from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { usePower } from '../../engine/src/core/ability.js'
import { endOfActivation } from '../../engine/src/core/battle.js'
import { beginActivation, endActivation } from '../../engine/src/core/mutate.js'
import { createBattle } from '../../engine/src/core/setup.js'
import { ABILITIES, ITEMS } from '../../engine/src/content/index.js'
import { STATUSES } from '../../engine/src/content/statuses.js'
import { SCENARIOS, scenarioOptions } from '../../engine/src/content/scenarios.js'

const FIXTURE = 'tools/fixtures/timed-effects.json'
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x))
const MAGE = 'hero.base.mage-fire'
/** the three items whose power puts a timed effect on its user, in the order the fixture fields them */
const KITS = { stoke: 'item.fire-gauntlet', sight: 'item.staff-of-the-ultimate-destroyer', coating: 'item.poison-coating' } as const
type Kit = keyof typeof KITS
const powerOf = (k: Kit) => ITEMS[KITS[k]]!.abilities[0]!
const statusOf = (k: Kit) => (ABILITIES[powerOf(k)]!.effects!.find((e) => e.kind === 'status.apply') as { statusId: string; value: number })
type E = { type: string; actor?: number | null; target?: number | null; statusId?: string; before?: number; after?: number; causeId?: string }

function played() {
  const kits = Object.keys(KITS) as Kit[]
  /* the Orphanage's own fielding (its map, its encounter, its zombie and its two civilians), with the three mages and their
     items in place of its hero — a painted scene, where the page draws every status as an icon under its unit */
  const opts = { ...(scenarioOptions(SCENARIOS['test.opening-orphanage']!, 0) as Record<string, unknown>), scenarioId: 'viewer.timed-effect-status-marks', heroes: kits.map(() => MAGE), heroItems: kits.map((k) => [KITS[k]]) }
  for (const k of ['heroProgress', 'heroBadges', 'heroMods', 'heroItemsUsed']) delete (opts as Record<string, unknown>)[k]
  const ctx = createBattle(opts as never)
  const heroes = ctx.state.units.filter((u) => u.typeId === MAGE)
  for (let round = 0; round < 5; round++) for (const [i, h] of heroes.entries()) {
    beginActivation(ctx, h.id, 'viewer.timed-effect-status-marks')
    if (round === 0) usePower(ctx, h.id, h.id, powerOf(kits[i]!))
    endActivation(ctx, h.id, 'viewer.timed-effect-status-marks'); endOfActivation(ctx, h.id)
  }
  return { ctx, holders: Object.fromEntries(kits.map((k, i) => [k, heroes[i]!.id])) as Record<Kit, number> }
}
function fixtureNow() {
  const { ctx, holders } = played()
  return { _about: 'GENERATED by test/viewer.timed-effect-status-marks.test.ts (TIMED_WRITE=1) from the engine — never hand-edit. Three Fire Mages at the Orphanage (its own fielding, with them in place of its hero), each carrying one of the three items whose power puts a timed effect on its user (the Fire Gauntlet: Stoke; the Staff of the Ultimate Destroyer: Perfect Sight; Poison Coating), fielded by createBattle; each uses its power in its first Activation and passes four more — moved by the engine\'s own functions, with no engine source typed here. `holders` names who holds which; `statuses` the status each power puts on.',
    seed: { mapId: ctx.state.mapId, replicate: 0, scenarioId: 'viewer.timed-effect-status-marks' }, holders,
    statuses: Object.fromEntries((Object.keys(KITS) as Kit[]).map((k) => [k, statusOf(k).statusId])), events: plain(ctx.events) }
}

describe('the timed effects have their own marks: what the engine\'s rows and lines give the page', () => {
  it('each of the three powers puts a status on its user whose row lends something and says what counts it down', () => {
    const stoke = STATUSES[statusOf('stoke').statusId]!, sight = STATUSES[statusOf('sight').statusId]!, coating = STATUSES[statusOf('coating').statusId]!
    expect(stoke).toMatchObject({ name: 'Stoke', countsDown: 'activation', decayPerPhase: 0 }); expect(stoke.lends!.triggers).toHaveLength(1)
    expect(sight).toMatchObject({ name: 'Perfect Sight', countsDown: 'activation', decayPerPhase: 0, lends: { doubles: ['precision'] } })
    expect(coating).toMatchObject({ name: 'Poison Coating', decayPerPhase: 0 }); expect(coating.countsDown).toBeUndefined(); expect(coating.lends!.triggers).toHaveLength(1)
    expect(statusOf('stoke').value).toBe(3); expect(statusOf('sight').value).toBe(3); expect(statusOf('coating').value).toBe(1)
  })
  it('the lines are the ordinary status lines: put on at 3, down to 2, to 1, to 0 and expired, by the holder\'s own Activations — and the coating stays at 1 for the Battle', () => {
    const { ctx, holders } = played(), EV = ctx.events as unknown as E[]
    const of = (k: Kit) => EV.filter((e) => e.statusId === statusOf(k).statusId).map((e) => [e.type, e.target, e.after ?? null])
    for (const k of ['stoke', 'sight'] as const) expect(of(k), k).toEqual([['status.applied', holders[k], 3], ['status.reduced', holders[k], 2], ['status.reduced', holders[k], 1], ['status.reduced', holders[k], 0], ['status.expired', holders[k], null]])
    expect(of('coating')).toEqual([['status.applied', holders.coating, 1]])
  })
  it('the viewer\'s dump carries, for every status whose engine row lends, what it lends and what counts it down — as the engine has them — and for no other', () => {
    const rows = JSON.parse(readFileSync('generated/static.json', 'utf8')).statusRows as Record<string, { lends?: unknown; countsDown?: string; countsAttackTag?: string; decayPerPhase?: number }>
    let lending = 0
    for (const [id, s] of Object.entries(STATUSES) as [string, { lends?: unknown; countsDown?: string; countsAttackTag?: string; decayPerPhase: number }][]) {
      expect(rows[id], id).toBeDefined()
      if (!s.lends) { expect(rows[id]!.lends, id).toBeUndefined(); continue }
      lending++
      expect(rows[id]!.lends, id).toEqual(plain(s.lends)); expect(rows[id]!.countsDown, id).toBe(s.countsDown); expect(rows[id]!.countsAttackTag, id).toBe(s.countsAttackTag); expect(rows[id]!.decayPerPhase, id).toBe(s.decayPerPhase)
    }
    expect(lending).toBeGreaterThanOrEqual(3)
  })
  it('the fixture is the engine\'s own lines, line for line', () => {
    const now = fixtureNow()
    if (process.env.TIMED_WRITE) writeFileSync(FIXTURE, JSON.stringify(now) + '\n')
    const kept = JSON.parse(readFileSync(FIXTURE, 'utf8'))
    expect(kept.holders).toEqual(now.holders); expect(kept.statuses).toEqual(now.statuses); expect(kept.events).toEqual(now.events)
  })
  it('the viewer page: Stoke shows a flame-marked buff with 3, then 2, then 1, and never Poison\'s dot; Perfect Sight and Poison Coating each show their own mark and count; the panel and the hover name each and say what it does; a status with no mark shows a neutral mark and is listed', () => {
    const out = execFileSync(process.execPath, ['--test', '--test-reporter=tap', 'tools/timed-effect-status-marks.test.mjs'], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 24, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })
    expect(out).toMatch(/# pass 6/); expect(out).toMatch(/# fail 0/)
    for (const line of out.split('\n').filter((l) => /^# \\?# /.test(l))) console.log(line.replace(/^# \\?# /, '  '))
  }, 170000)
})
