// viewer.bar-shows-every-effect (engine backlog; engine DECISIONS.md 2026-10-03 'the action bar: the moves grey slightly once
// the move is done, nothing else greys; every action shows all it does; the Soldier holds no sword'). Andrew: "some of the
// information and some of the actions are missing. For example, a dagger giving you one protection is not shown in the dagger
// attack." The engine's side — what the bar is drawn from, and nothing new: a fielded unit holds one list of action ids
// (core/action.ts grantedActionIds) and its triggers — its row's own, then those its items bring (core/items.ts applyItems),
// then its badges'. The Dagger brings 'onAttack: gain 1 Protection', scoped to its Stab. This file makes the audit's roster
// from the engine (the 24 base heroes with their kits, the Flaming Longsword on its takers, the six opening battles as set up)
// and holds the committed roster (tools/fixtures/bar-audit-roster.json) to it; the viewer's half
// (../viewer/tools/bar-shows-every-effect.test.mjs) runs the audit (tools/bar-audit.mjs) over the page; the sandbox's half
// (../kingdom/tools/bar-shows-every-effect.verify.mjs) reads the bar against the engine's own units on the built
// BATTLE-SANDBOX.html. Imports no page code.
//
//   BAR_AUDIT_WRITE=1 npm test -- viewer.bar-shows-every-effect     rewrites the roster from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createBattle } from '../../engine/src/core/setup.js'
import { grantedActionIds } from '../../engine/src/core/action.js'
import { ACTIONS, ITEMS, UNITS } from '../../engine/src/content/index.js'
import { scenarioDef, scenarioOptions } from '../../engine/src/content/scenarios.js'
import { OPENING_TAKERS, withOpeningItem } from '../../engine/src/content/opening-party.js'
import OPENING from '../../progression/OPENING-PARTY.json' with { type: 'json' }

const ROSTER = 'tools/fixtures/bar-audit-roster.json'
type Ctx = ReturnType<typeof createBattle>
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x))
/** one battle as the engine set it up: its events, and each unit's own action list and triggers */
const battleOf = (label: string, ctx: Ctx) => ({ label, events: plain(ctx.events),
  units: ctx.state.units.map((u) => ({ id: u.id, typeId: u.typeId, name: u.name, side: u.side, actions: [...grantedActionIds(ctx, u)], triggers: plain(u.triggers) })) })
function rosterNow() {
  const pool = OPENING.pool as string[], battles = []
  // the 24 base heroes, each wearing its row's own kit, six to a battle
  for (let k = 0; k < pool.length; k += 6) battles.push(battleOf(`base heroes ${k + 1} to ${Math.min(pool.length, k + 6)}`, createBattle({ seed: 1, heroes: pool.slice(k, k + 6), enemies: ['unit.zombie'] })))
  // the opening's named reward on each class that may take it
  for (const [itemId, takers] of Object.entries(OPENING_TAKERS)) for (const cls of takers) {
    const hero = pool.find((id) => (UNITS[id]!.tags ?? []).includes(cls))!
    battles.push(battleOf(`${ITEMS[itemId]!.name} on ${UNITS[hero]!.name}`, createBattle({ seed: 1, heroes: [hero], heroItems: [withOpeningItem(hero, undefined, itemId)], enemies: ['unit.zombie'] })))
  }
  // the six opening battles as set up: the party drafted by then, the placed civilians, the enemies on the board
  for (const s of ['orphanage', 'lumberjack', 'bridge', 'cavern-trail', 'gates', 'cathedral']) battles.push(battleOf(`the opening: ${s}`, createBattle(scenarioOptions(scenarioDef('test.opening-' + s), 1))))
  return { _about: 'GENERATED by test/viewer.bar-shows-every-effect.test.ts (BAR_AUDIT_WRITE=1) from the engine — never hand-edit. The units the opening run can field, each with the engine\'s own list of its actions and triggers; tools/bar-audit.mjs reads the action bar against it.', battles }
}

describe('every action on the bar shows everything it does', () => {
  it('the engine: the Dagger brings "onAttack: gain 1 Protection" to its Stab, and a fielded unit carries it', () => {
    const t = ITEMS['item.dagger']!.triggers.find((x) => x.onlyWithAttack === 'attack.dagger.stab')!
    expect(t).toMatchObject({ hook: 'onAttack', chance: 100, select: 'self', effect: { kind: 'status.apply', statusId: 'status.protection', value: 1 } })
    const ctx = createBattle(scenarioOptions(scenarioDef('test.opening-orphanage'), 1))
    const holder = ctx.state.units.find((u) => u.actions.includes('attack.dagger.stab'))!
    expect(holder.triggers.map((x) => x.id)).toContain(t.id)
  })
  it('the roster the audit reads is the engine\'s: every base hero with its kit, the reward\'s takers, the six opening battles', () => {
    const now = rosterNow()
    if (process.env.BAR_AUDIT_WRITE) writeFileSync(ROSTER, JSON.stringify(now) + '\n')
    const held = JSON.parse(readFileSync(ROSTER, 'utf8'))
    expect(held).toEqual(plain(now))
    const fielded = new Set(now.battles.flatMap((b) => b.units.map((u) => u.typeId)))
    for (const id of OPENING.pool as string[]) expect(fielded.has(id), id).toBe(true)
    for (const itemId of Object.keys(OPENING_TAKERS)) expect(now.battles.some((b) => b.units.some((u) => u.triggers.some((t) => t.source === itemId))), itemId + ' is held, and brings its triggers').toBe(true)
    for (const civilian of ['hero.fixed.orphans', 'hero.fixed.school-teacher', 'hero.fixed.lumberjack-and-wife', 'hero.fixed.lumberjacks-wife']) expect(fielded.has(civilian), civilian).toBe(true)
    // every action a rostered unit holds has its row in the dump the page is built from, unchanged; and every item's triggers
    const s = JSON.parse(readFileSync('generated/static.json', 'utf8')) as { actions: Record<string, unknown>; items: Record<string, { triggers: unknown[] }> }
    for (const b of now.battles) for (const u of b.units) for (const a of u.actions) expect(s.actions[a], a).toEqual(plain(ACTIONS[a]))
    for (const [id, row] of Object.entries(ITEMS)) expect(s.items[id]!.triggers, id).toEqual(plain(row.triggers))
  })
  it('the viewer page: the audit finds no action without a button and nothing an action does left unsaid; the Stab reads "gain 1 Protection"', () => {
    const out = execFileSync(process.execPath, ['--test', '--test-reporter=tap', 'tools/bar-shows-every-effect.test.mjs'], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 24, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })
    // 2026-10-05, capability.damage-from-two-stats (engine item): this read `expect(out).toMatch(/# pass 4/)` - the tool's four
    // tests. It has a fifth now (a damage line says every term of its sum); all five must pass, none fail.
    // 2026-10-05, capability.summons (engine item): a sixth test (a summon is said on the bar); this read /# pass 5/.
    // 2026-10-05, capability.raise-lower-magic (engine item): a seventh test (a side's party stat changing is said); this read /# pass 6/.
    // 2026-10-05, capability.his-weapons-small-clauses (engine item): an eighth test (the corpse destroyed on a kill, a status removed by a stat's amount); this read /# pass 7/.
    expect(out).toMatch(/# pass 8/); expect(out).toMatch(/# fail 0/)
  }, 170000)
  it('the sandbox: the expect line, read against the engine\'s own units on the built BATTLE-SANDBOX.html (the Orphanage)', () => {
    mkdirSync('../kingdom/scratch', { recursive: true })
    execFileSync(process.execPath, ['tools/build-sandbox.mjs', 'scratch/bar-shows-every-effect.html'], { cwd: '../kingdom', stdio: 'pipe' })
    const out = execFileSync(process.execPath, ['tools/bar-shows-every-effect.verify.mjs', 'scratch/bar-shows-every-effect.html'], { cwd: '../kingdom', encoding: 'utf8', maxBuffer: 1 << 26 })
    expect(out).toMatch(/bar-shows-every-effect: .*passed/)
  }, 170000)
})
