// viewer.enemy-type-moves-together (engine backlog; engine DECISIONS.md 2026-10-03 'posted: which motions enemies and heroes
// need, and enemies of one type move together', 'the post's twelve questions answered' (10-12) and 'Back Flip's rules; enemies
// only move together; the motion work comes first'). Andrew: "During the enemy turn I would like for all of the enemies of a
// type to move at the same time. What I mean by this is only the move actions. They can still be determined in the order
// they should have been determined, but we're just displaying it as if they're all moving at the same time." / "functionally
// it should be exactly the same." Display only: the engine, its log and every result are untouched — nothing of the engine
// changes, and this file holds what the display stands on: the engine decides the enemies one Activation after another
// (each whole before the next begins), a unit's type is its own row (a Zombie and a Fast Zombie are two), and its own battle
// of five Zombies and four Bloodhounds is the fixture the page test plays (tools/fixtures/enemies-together.json, made here).
// The viewer's half is ../viewer/tools/enemy-type-moves-together.test.mjs (the grouped playback, and the proof that it ends
// on the same state as the one-at-a-time playback); the sandbox's half ../kingdom/tools/enemy-type-moves-together.verify.mjs
// plays the built BATTLE-SANDBOX.html and reads the board against the engine's battle after every Enemy Phase.
//
//   ENEMIES_TOGETHER_WRITE=1 npm test -- viewer.enemy-type-moves-together     rewrites the fixture from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createCustomBattle } from '../../engine/src/core/setup.js'
import { runBattle } from '../../engine/src/core/battle.js'
import { UNITS } from '../../engine/src/content/index.js'

const FIXTURE = 'tools/fixtures/enemies-together.json'
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x))
const hexAt = (col: number, row: number) => row * 16 + col
/** three heroes on the left of the open field; five Zombies in a column, four Bloodhounds behind them */
function fiveAndFour() {
  // Law 10, 2026-10-05 - engine content.dwarf-elf-fey-badges-act (engine DECISIONS.md 2026-10-05 'a prone unit only stands; … Dwarf,
  // Elf and Fey act; …': "6. They should act."): the two Iron Dwarves stood at column 3. A Dwarf has 1 less Movement now, so from
  // there they stopped a hex short on Turn 1 and only two of the five Zombies reached a hero to attack - the scene the page test
  // plays is "each Zombie walks up and attacks". The scene is said as what it is: the Dwarves start one column nearer (4), where
  // their walk ends on the hexes it ended on before, and the first Enemy Phase is again five Zombies walking and attacking and
  // four Bloodhounds walking. No assertion of either file is changed.
  // was: const heroes = [{ type: 'hero.base.warrior-iron', hex: hexAt(3, 6) }, { type: 'hero.base.ranger-scantily', hex: hexAt(2, 8) }, { type: 'hero.base.warrior-iron', hex: hexAt(3, 10) }]
  const heroes = [{ type: 'hero.base.warrior-iron', hex: hexAt(4, 6) }, { type: 'hero.base.ranger-scantily', hex: hexAt(2, 8) }, { type: 'hero.base.warrior-iron', hex: hexAt(4, 10) }]
  const enemies = [...[3, 5, 7, 9, 11].map((r) => ({ type: 'unit.zombie', hex: hexAt(10, r) })), ...[4, 6, 8, 10].map((r) => ({ type: 'unit.bloodhound', hex: hexAt(13, r) }))]
  const ctx = createCustomBattle(heroes, enemies, { replicate: 1 })
  runBattle(ctx)
  return ctx
}
function fixtureNow() {
  const ctx = fiveAndFour()
  return { _about: 'GENERATED by test/viewer.enemy-type-moves-together.test.ts (ENEMIES_TOGETHER_WRITE=1) from the engine — never hand-edit. The engine\'s own battle on the open field (createCustomBattle, replicate 1): two Iron Dwarves and a Hunter against five Zombies and four Bloodhounds, the computer playing both sides, whole.',
    seed: { mapId: ctx.state.mapId }, outcome: ctx.state.outcome, events: plain(ctx.events) }
}
type E = { type: string; actor?: number; phase?: string; turn?: number }

describe('enemies of one type are shown moving together: what the engine decides is untouched', () => {
  it('the engine decides the enemies one Activation after another, each whole before the next begins — five Zombies, then four Bloodhounds', () => {
    const ctx = fiveAndFour(), EV = ctx.events as E[]
    const begin = EV.findIndex((e) => e.type === 'phase.begin' && e.phase === 'enemy'), end = EV.findIndex((e, i) => i > begin && e.type === 'phase.end.begin')
    const typeOf = (id: number) => ctx.state.units[id]!.typeId
    const acts = EV.slice(begin, end).filter((e) => e.type === 'activation.begin').map((e) => typeOf(e.actor!))
    expect(acts).toEqual([...Array(5).fill('unit.zombie'), ...Array(4).fill('unit.bloodhound')])
    /* no Activation begins inside another: begin, …, end, begin, …, end */
    let open: number | null = null
    for (const e of EV.slice(begin, end)) {
      if (e.type === 'activation.begin') { expect(open).toBe(null); open = e.actor! }
      if (e.type === 'activation.end') { expect(e.actor).toBe(open); open = null }
    }
    expect(open).toBe(null)
  })
  it('a unit\'s type is its own row: a Zombie and a Fast Zombie are two types', () => {
    const rows = UNITS as Record<string, { typeId: string; name: string }>
    expect(rows['unit.zombie']!.typeId).toBe('unit.zombie'); expect(rows['unit.fast-zombie']!.typeId).toBe('unit.fast-zombie')
    expect(rows['unit.zombie']!.typeId).not.toBe(rows['unit.fast-zombie']!.typeId)
  })
  it('the fixture is the engine\'s own battle, line for line', () => {
    const now = fixtureNow()
    if (process.env.ENEMIES_TOGETHER_WRITE) writeFileSync(FIXTURE, JSON.stringify(now) + '\n')
    expect(JSON.parse(readFileSync(FIXTURE, 'utf8'))).toEqual(now)
  })
  it('the viewer page: the groups\' walks start together, their attacks follow, a free attack freezes the group — and the grouped playback ends on the same state as the one-at-a-time playback', () => {
    const out = execFileSync(process.execPath, ['--test', '--test-reporter=tap', 'tools/enemy-type-moves-together.test.mjs'], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 26, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })
    expect(out).toMatch(/# pass 9/); expect(out).toMatch(/# fail 0/)
  }, 600000)
  it('the sandbox: on the built BATTLE-SANDBOX.html the Enemy Phase is shown grouped and the board is the engine\'s battle after every phase', () => {
    mkdirSync('../kingdom/scratch', { recursive: true })
    execFileSync(process.execPath, ['tools/build-sandbox.mjs', 'scratch/enemy-type-moves-together.html'], { cwd: '../kingdom', stdio: 'pipe' })
    const out = execFileSync(process.execPath, ['tools/enemy-type-moves-together.verify.mjs', 'scratch/enemy-type-moves-together.html'], { cwd: '../kingdom', encoding: 'utf8', maxBuffer: 1 << 26 })
    expect(out).toMatch(/enemy-type-moves-together: .*passed/)
  }, 300000)
})
