// viewer.bar-shows-tag-requirement (engine backlog, filed 2026-10-04 from the engine worker's finding landing
// capability.unit-trigger-with-tag; engine DECISIONS.md 2026-10-04 'after the backlog run: ... a trigger on the hero with a tag
// requirement ...', Andrew: "it only triggers when you're using something that has the tag melee"; and 2026-10-03 'the action
// bar: ... every action shows all it does' - the bar shows every effect an action will have and none it will not).
// The engine reads `onlyWithTag` on a unit's trigger (core/trigger.ts fireTriggers) and one function says what "has the tag"
// means (core/action.ts carriesTag; engine SWITCHES attackHasTag). The engine's side - what the bar is drawn from, and
// nothing new: this file makes the item's roster from the engine (a Ranger wearing the Burning Touch with its Shortbow in
// hand, the same Ranger without it, one wearing the Bleeding Strike, a Brawler in Pharaoh's Gauntlets wearing the Burning
// Touch) and holds the committed roster (tools/fixtures/bar-tag-requirement-roster.json) to it; it holds the dump's table of
// the engine's answers (generated/static.json tagCarriers: for each tag a trigger requires, the actions that carry it) to
// carriesTag itself, action by action. The viewer's half (../viewer/tools/bar-shows-tag-requirement.test.mjs) reads the bar
// and the panel on the page; the sandbox's half (../kingdom/tools/bar-shows-tag-requirement.verify.mjs) holds the built
// BATTLE-SANDBOX.html to the same table. Imports no page code.
//
//   BAR_TAG_WRITE=1 npm test -- viewer.bar-shows-tag-requirement     rewrites the roster from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createBattle } from '../../engine/src/core/setup.js'
import { carriesTag, grantedActionIds } from '../../engine/src/core/action.js'
import { ACTIONS, BADGES, ITEMS, UNITS } from '../../engine/src/content/index.js'

const ROSTER = 'tools/fixtures/bar-tag-requirement-roster.json'
const RANGER = 'hero.base.ranger-nature', BRAWLER = 'hero.base.warrior-brawler'
const TOUCH = 'item.rune-burning-touch', STRIKE = 'item.rune-bleeding-strike', GAUNTLETS = 'item.pharaohs-gauntlets'
type Ctx = ReturnType<typeof createBattle>
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x))
/** one battle as the engine set it up: its events, and each unit's own action list and triggers (the bar-audit roster's shape) */
const battleOf = (label: string, ctx: Ctx) => ({ label, events: plain(ctx.events),
  units: ctx.state.units.map((u) => ({ id: u.id, typeId: u.typeId, name: u.name, side: u.side, actions: [...grantedActionIds(ctx, u)], triggers: plain(u.triggers) })) })
/** one hero in its row's own kit with `more` added, against one zombie */
const fielded = (label: string, hero: string, more: string[]) =>
  battleOf(label, createBattle({ seed: 1, heroes: [hero], heroItems: [[...(UNITS[hero]!.defaultItems ?? []), ...more]], enemies: ['unit.zombie'] }))
function rosterNow() {
  return { _about: 'GENERATED by test/viewer.bar-shows-tag-requirement.test.ts (BAR_TAG_WRITE=1) from the engine - never hand-edit. Four heroes as the engine fields them, each with the engine\'s own list of its actions and triggers: a trigger with a tag requirement, the same hero without it, a trigger with none, and two requirements on one hero; tools/bar-shows-tag-requirement.test.mjs reads the action bar and the panel against it.',
    battles: [
      fielded('the Burning Touch with a Shortbow', RANGER, [TOUCH]),
      fielded('the same hero without it', RANGER, []),
      fielded('the Bleeding Strike with a Shortbow', RANGER, [STRIKE]),
      fielded('Pharaoh\'s Gauntlets and the Burning Touch', BRAWLER, [GAUNTLETS, TOUCH]),
    ] }
}
/** every tag a trigger in the engine's content requires - on a unit's row, an item's, a badge's (the three that bring triggers) */
function requiredTags(): string[] {
  const tags = new Set<string>()
  for (const table of [UNITS, ITEMS, BADGES] as Record<string, { triggers?: readonly { onlyWithTag?: string }[] }>[])
    for (const row of Object.values(table)) for (const t of row.triggers ?? []) if (t.onlyWithTag !== undefined) tags.add(t.onlyWithTag)
  return [...tags].sort()
}

describe('a trigger with a tag requirement is listed only on the attacks that have the tag', () => {
  it('the engine: the Burning Touch requires melee, the Gauntlets brawl; the Shortbow\'s shots carry neither and the Punch both', () => {
    expect(ITEMS[TOUCH]!.triggers).toEqual([expect.objectContaining({ hook: 'onHit', onlyWithTag: 'melee', effect: { kind: 'status.apply', statusId: 'status.burn', value: 1 } })])
    expect(ITEMS[GAUNTLETS]!.triggers).toEqual([expect.objectContaining({ hook: 'onHit', onlyWithTag: 'brawl' })])
    expect(ITEMS[STRIKE]!.triggers[0]!.onlyWithTag).toBeUndefined()
    expect(ITEMS['item.shortbow']!.grants.length).toBeGreaterThan(0)
    for (const shot of ITEMS['item.shortbow']!.grants) { expect(carriesTag(ACTIONS[shot], 'melee'), shot).toBe(false); expect(carriesTag(ACTIONS[shot], 'brawl'), shot).toBe(false) }
    expect(carriesTag(ACTIONS['attack.punch'], 'melee')).toBe(true); expect(carriesTag(ACTIONS['attack.punch'], 'brawl')).toBe(true)
    expect(requiredTags()).toEqual(expect.arrayContaining(['brawl', 'melee']))
  })
  it('the roster the page test reads is the engine\'s: the bearer holds the bow\'s shots, the Punch and the rune\'s trigger', () => {
    const now = rosterNow()
    if (process.env.BAR_TAG_WRITE) writeFileSync(ROSTER, JSON.stringify(now) + '\n')
    const held = JSON.parse(readFileSync(ROSTER, 'utf8'))
    expect(held).toEqual(plain(now))
    const hero = (k: number) => now.battles[k]!.units.find((u) => u.side === 'hero')!
    expect(hero(0).actions).toEqual(expect.arrayContaining([...ITEMS['item.shortbow']!.grants, 'attack.punch']))
    expect(hero(0).triggers.map((t) => t.id)).toEqual(ITEMS[TOUCH]!.triggers.map((t) => t.id))
    expect(hero(1).actions).toEqual(hero(0).actions); expect(hero(1).triggers).toEqual([])
    expect(hero(2).triggers.map((t) => t.id)).toEqual(ITEMS[STRIKE]!.triggers.map((t) => t.id))
    expect(hero(3).triggers.map((t) => t.onlyWithTag).sort()).toEqual(['brawl', 'melee'])
  })
  it('the dump: static.json tagCarriers is the engine\'s own answer - carriesTag, for every tag a trigger requires, over every action', () => {
    const s = JSON.parse(readFileSync('generated/static.json', 'utf8')) as { tagCarriers?: Record<string, string[]>; actions: Record<string, unknown> }
    expect(s.tagCarriers, 'generated/static.json carries tagCarriers (npm run static)').toBeDefined()
    expect(Object.keys(s.tagCarriers!).sort()).toEqual(requiredTags())
    for (const tag of requiredTags()) {
      expect(s.tagCarriers![tag], tag).toEqual(Object.keys(ACTIONS).filter((id) => carriesTag(ACTIONS[id], tag)))
      expect(s.tagCarriers![tag]!.length, tag).toBeGreaterThan(0)
    }
    // the rows themselves are still copied unchanged: the table is beside them, not on them
    for (const id of ['attack.punch', ...ITEMS['item.shortbow']!.grants]) expect(s.actions[id], id).toEqual(plain(ACTIONS[id]))
  })
  it('the viewer page: the bow shot lists no Burn, the Punch lists "On hit: apply 1 Burn", the panel says "only with a melee attack"', () => {
    const out = execFileSync(process.execPath, ['--test', '--test-reporter=tap', 'tools/bar-shows-tag-requirement.test.mjs'], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 24, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })
    expect(out).toMatch(/# pass 5/); expect(out).toMatch(/# fail 0/)
  }, 170000)
  it('the sandbox: the built BATTLE-SANDBOX.html hands its battle screen the same table, and its bar reads it', () => {
    mkdirSync('../kingdom/scratch', { recursive: true })
    execFileSync(process.execPath, ['tools/build-sandbox.mjs', 'scratch/bar-shows-tag-requirement.html'], { cwd: '../kingdom', stdio: 'pipe' })
    const out = execFileSync(process.execPath, ['tools/bar-shows-tag-requirement.verify.mjs', 'scratch/bar-shows-tag-requirement.html'], { cwd: '../kingdom', encoding: 'utf8', maxBuffer: 1 << 26 })
    expect(out).toMatch(/bar-shows-tag-requirement: .*passed/)
  }, 170000)
})
