// viewer.free-attack-kind-words (engine backlog; found landing capability.counterattack-and-fend, 2026-10-04 — engine SWITCHES.md
// freeAttackKindOnTheLine: a counterattack and a fend reuse the attack-of-opportunity log line, `aoo.provoked`, with an `as`
// field naming the kind, "so the viewer plays them today (it words each as an attack of opportunity until a viewer item
// gives them their own words and the condition its icon)"; Andrew, engine DECISIONS.md 2026-09-28 'counterattack, special free
// attacks, the opening six, shields, custom weapons').
// Display only: no engine change. This file holds what the display stands on — the engine's own lines: a counterattack's and
// a fend's `aoo.provoked` carry `as` and name their rule as cause, an attack of opportunity's carries no `as`; the swing
// that follows is the holder's own `attack.declared`; and a unit has the kind UP while its `counterattack` / `fend` stat is
// above 0 — a modifier the power's `statmod.added` line adds and `statmod.expired` takes away — and makes the fixture the
// page test plays: tools/fixtures/free-attack-kinds.json, the engine's own two fieldings (test.counterattack: a paladin
// raises his Counterattack and answers the zombies that swing at him; test.fend: a unit with the test Fend power fends off
// the zombies that walk up to it), each on replicate 0 — the first, not sought.
// The viewer's half is ../viewer/tools/free-attack-kind-words.test.mjs.
//
//   FREE_ATTACK_WRITE=1 npm test -- viewer.free-attack-kind-words     rewrites the fixture from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { createBattle } from '../../engine/src/core/setup.js'
import { runBattle } from '../../engine/src/core/battle.js'
import { SCENARIOS, scenarioOptions } from '../../engine/src/content/scenarios.js'

const FIXTURE = 'tools/fixtures/free-attack-kinds.json'
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x))
const KINDS = { counterattack: 'test.counterattack', fend: 'test.fend' } as const
/* Law 10, 2026-10-04 — capability.free-attack-accuracy (engine item; engine DECISIONS.md 2026-09-28, the Armory Ledger's rules: "'+10
   counterattack' on a weapon is +10 Accuracy on your counterattacks."): this read
     function played(kind) { const ctx = createBattle(scenarioOptions(SCENARIOS[KINDS[kind]]!, 0)); runBattle(ctx); return ctx }
   — replicate 0, typed. The paladin's Longsword gives his counterattack +10 now; on replicate 0 he wins on Turn 2, before the
   power's modifier has run out, and the lines this file and the page test read (an answer, and the kind running out) are not all
   there. Each fielding is played on the lowest replicate whose battle holds both KINDS of line — replicates read from 0 upward,
   12 at most — and the fixture records which. Nothing here asks who wins. */
const HOLDS = (kind: string, EV: readonly { type: string; as?: string; stat?: string }[]) => EV.some((e) => e.type === 'aoo.provoked' && e.as === kind) && EV.some((e) => e.type === 'statmod.expired' && e.stat === kind)
const REPLICATE: Partial<Record<keyof typeof KINDS, number>> = {}
function played(kind: keyof typeof KINDS) {
  for (let r = REPLICATE[kind] ?? 0; r < 12; r++) {
    const ctx = createBattle(scenarioOptions(SCENARIOS[KINDS[kind]]!, r)); runBattle(ctx)
    if (HOLDS(kind, ctx.events as never)) { REPLICATE[kind] = r; return ctx }
  }
  throw new Error(`${KINDS[kind]}: no replicate 0-11 holds an answer and the ${kind} running out`)
}
function fixtureNow() {
  const out: Record<string, unknown> = { _about: 'GENERATED by test/viewer.free-attack-kind-words.test.ts (FREE_ATTACK_WRITE=1) from the engine — never hand-edit. The engine\'s own fieldings test.counterattack and test.fend (createBattle of each scenario, on the lowest replicate whose battle holds an answer of the kind and the kind running out — the seed below says which): a paladin raises the Longsword\'s Counterattack and answers the zombies that attack him; a unit with the test Fend power fends off the zombies that walk up to it.' }
  for (const kind of Object.keys(KINDS) as (keyof typeof KINDS)[]) { const ctx = played(kind); out[kind] = { seed: { mapId: ctx.state.mapId, replicate: REPLICATE[kind]!, scenarioId: KINDS[kind] }, outcome: ctx.state.outcome, events: plain(ctx.events) } }
  return out
}
type E = { type: string; actor?: number; target?: number; as?: string; causeId?: string; attackId?: string; stat?: string; free?: boolean; value?: number }
const page = (file: string) => execFileSync(process.execPath, ['--test', '--test-reporter=tap', file], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 26, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })

describe('a counterattack and a fend are worded by their kind: what the engine\'s lines say', () => {
  it('the line names its kind: `as` and the rule as its cause on a counterattack and a fend; the swing that follows is the holder\'s own attack, free, of the same kind; the unit had the kind up — its stat raised by the power\'s own line', () => {
    for (const kind of Object.keys(KINDS) as (keyof typeof KINDS)[]) {
      const EV = played(kind).events as unknown as E[], lines = EV.map((e, i) => ({ e, i })).filter((x) => x.e.type === 'aoo.provoked')
      expect(lines.length, kind).toBeGreaterThan(0)
      for (const { e, i } of lines) {
        expect(e.as).toBe(kind); expect(e.causeId).toBe('rule.' + kind)
        const swing = EV.slice(i + 1).find((x) => x.type === 'attack.declared')!
        expect(swing.actor).toBe(e.actor); expect(swing.target).toBe(e.target); expect(swing.attackId).toBe(e.attackId); expect(swing.free).toBe(true); expect(swing.as).toBe(kind)
        /* up: more `statmod.added` than `statmod.expired` of the kind's stat on the holder before this line */
        const up = EV.slice(0, i).filter((x) => x.actor === e.actor && x.stat === kind).reduce((n, x) => n + (x.type === 'statmod.added' ? 1 : x.type === 'statmod.expired' ? -1 : 0), 0)
        expect(up, `${kind}: up when it answered`).toBeGreaterThan(0)
      }
      expect(EV.some((x) => x.type === 'statmod.expired' && x.stat === kind), `${kind}: it runs out`).toBe(true)
    }
  })
  it('an attack of opportunity\'s line carries no `as` (the Cathedral\'s recording)', () => {
    const ctx = createBattle(scenarioOptions(SCENARIOS['test.opening-cathedral']!, 10)); runBattle(ctx)
    const aoo = (ctx.events as unknown as E[]).filter((e) => e.type === 'aoo.provoked')
    const plainOnes = aoo.filter((e) => e.causeId === 'movement.aoo')
    expect(plainOnes.length).toBeGreaterThan(0)
    for (const e of plainOnes) expect(e.as).toBeUndefined()
    for (const e of aoo.filter((x) => x.causeId !== 'movement.aoo')) { expect(['counterattack', 'fend']).toContain(e.as); expect(e.causeId).toBe('rule.' + e.as) }
  })
  it('the fixture is the engine\'s own two battles, line for line', () => {
    const now = fixtureNow()
    if (process.env.FREE_ATTACK_WRITE) writeFileSync(FIXTURE, JSON.stringify(now) + '\n')
    const kept = JSON.parse(readFileSync(FIXTURE, 'utf8'))
    for (const kind of Object.keys(KINDS)) expect(kept[kind].events, kind).toEqual((now[kind] as { events: unknown }).events)
  })
  it('the viewer page: the log, the floating text and the bar\'s tooltip say Counterattack, Fend or attack of opportunity by the line\'s own kind, and a unit with one up shows it on its token, its panel and its card', () => {
    const out = page('tools/free-attack-kind-words.test.mjs')
    expect(out).toMatch(/# pass 5/); expect(out).toMatch(/# fail 0/)
    for (const line of out.split('\n').filter((l) => /^# \\?# /.test(l))) console.log(line.replace(/^# \\?# /, '  '))
  }, 600000)
})
