// viewer.plays-turned-units (engine backlog; found 2026-10-04 by the engine worker — viewer SWITCHES.md openingReplayPlayableSeed:
// "the viewer does not draw a transformation"). rule.afflictions-at-zero (engine DECISIONS.md 2026-10-01 'the afflictions at 0
// Health'): a hero carrying Lycanthropy or Vampirism, taken to 0 Health, becomes its affliction's form — "the bestiary's
// stats and powers, no hero gear", at full Health, on the side its Luck roll says — and is itself again when it falls or when
// the battle ends. The engine says each in ONE line (unit.transformed, unit.reverted).
// Display only: the engine is untouched. This file holds what the display stands on — the two lines' own fields, and the
// engine's unit either side of each (what the board must then show) — and makes the fixture the page test plays:
// tools/fixtures/turned-heroes.json, the engine's own battle of four afflicted heroes against six Werewolves on the open
// field (createBattle, replicate 0 — the first, not sought), in which all four are turned (two into Werewolves, two into
// Vampires) and are themselves again at the battle's end.
// The viewer's half is ../viewer/tools/plays-turned-units.test.mjs (it plays that battle and the Cavern Trail's own
// recording and reads the unit before, during and after).
//
//   TURNED_WRITE=1 npm test -- viewer.plays-turned-units     rewrites the fixture from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { createBattle } from '../../engine/src/core/setup.js'
import { runBattle } from '../../engine/src/core/battle.js'
import { UNITS } from '../../engine/src/content/index.js'

const FIXTURE = 'tools/fixtures/turned-heroes.json'
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x))
const OPTS = { replicate: 0, mapId: 'map.open', heroes: ['hero.base.warrior-iron', 'hero.base.ranger-scantily', 'hero.base.priest-armored', 'hero.base.warrior-fearsome'], enemies: Array(6).fill('unit.werewolf'), enemyCount: 6,
  heroBadges: [['badge.lycanthropy'], ['badge.vampirism'], ['badge.lycanthropy'], ['badge.vampirism']] }
const battle = () => createBattle(plain(OPTS) as never)
function fixtureNow() {
  const ctx = battle(); runBattle(ctx)
  return { _about: 'GENERATED by test/viewer.plays-turned-units.test.ts (TURNED_WRITE=1) from the engine — never hand-edit. The engine\'s own battle on the open field (createBattle, replicate 0): an Iron Dwarf and a Battle Chaplain carrying Lycanthropy, a Hunter and a Fearsome warrior carrying Vampirism, against six Werewolves. Each hero taken to 0 Health becomes its affliction\'s form on the enemy side (unit.transformed) and is itself again when the battle ends (unit.reverted).',
    seed: { mapId: ctx.state.mapId, replicate: 0 }, outcome: ctx.state.outcome, events: plain(ctx.events) }
}
type E = { type: string; actor?: number; from?: string; into?: string; side?: string; fromSide?: string; hp?: number; maxHp?: number; badgeId?: string; reason?: string }
const page = (file: string) => execFileSync(process.execPath, ['--test', '--test-reporter=tap', file], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 26, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })

describe('a hero turned by an affliction: what the engine\'s two lines say, and its unit either side of them', () => {
  it("unit.transformed names the unit, the affliction, what it was and what it is, its side and its Health — the form's own full Health; from then on the unit acts in the form's side's Phase with the form's attacks", () => {
    const ctx = battle(); runBattle(ctx)
    const EV = ctx.events as unknown as (E & { phase?: string; attackId?: string; typeId?: string })[]
    const entered = new Map(EV.filter((e) => e.type === 'unit.enter').map((e) => [e.actor!, e.typeId!]))
    const turned = EV.map((e, i) => ({ e, i })).filter((x) => x.e.type === 'unit.transformed')
    expect(turned.length).toBe(4)
    for (const { e, i } of turned) {
      const row = (UNITS as Record<string, { name: string; maxHp: number; maxStamina?: number; attacks: (string | { id: string })[] }>)[e.into!]!
      expect(e.from).toBe(entered.get(e.actor!)); expect(['badge.lycanthropy', 'badge.vampirism']).toContain(e.badgeId)
      expect(e.into).toBe(e.badgeId === 'badge.lycanthropy' ? 'unit.werewolf' : 'unit.vampire')
      expect(['hero', 'enemy']).toContain(e.side); expect(e.maxHp).toBe(row.maxHp); expect(e.hp).toBe(row.maxHp)
      const back = EV.findIndex((x, k) => k > i && x.type === 'unit.reverted' && x.actor === e.actor)
      const mine = EV.slice(i + 1, back).filter((x) => x.actor === e.actor)
      const formAttacks = row.attacks.map((x) => typeof x === 'string' ? x : x.id)
      for (const x of mine) { if (x.type === 'activation.begin') expect(x.phase, "it acts in its new side's Phase").toBe(e.side)
        if (x.type === 'attack.declared') expect(formAttacks, "it attacks with the form's attacks").toContain(x.attackId) }
    }
    expect(turned.some(({ e, i }) => EV.slice(i).some((x) => x.type === 'attack.declared' && x.actor === e.actor)), 'a turned unit attacked as its form').toBe(true)
  })
  it('unit.reverted names what it was as a form and what it is again, both sides, why, and the Health it comes back with', () => {
    const ctx = battle(); runBattle(ctx)
    const EV = ctx.events as unknown as E[], back = EV.filter((e) => e.type === 'unit.reverted'), turned = EV.filter((e) => e.type === 'unit.transformed')
    expect(back.length).toBe(turned.length)
    for (const e of back) { const t = turned.find((x) => x.actor === e.actor)!, u = ctx.state.units[e.actor!]! as unknown as Record<string, unknown>
      expect(e.from).toBe(t.into); expect(e.into).toBe(t.from); expect(e.fromSide).toBe(t.side); expect(e.side).toBe('hero'); expect(e.badgeId).toBe(t.badgeId)
      expect(['fell', 'battleEnd']).toContain(e.reason)
      expect(u.typeId).toBe(e.into); expect(u.side).toBe('hero'); expect(u.hp).toBe(e.hp); expect(u.maxHp).toBe(e.maxHp) }
    expect(EV.at(-1)!.type).toBe('battle.end')
  })
  it('the fixture is the engine\'s own battle, line for line', () => {
    const now = fixtureNow()
    if (process.env.TURNED_WRITE) writeFileSync(FIXTURE, JSON.stringify(now) + '\n')
    const kept = JSON.parse(readFileSync(FIXTURE, 'utf8'))
    expect(kept.events.length).toBe(now.events.length); expect(kept.events).toEqual(now.events); expect(kept.outcome).toBe(now.outcome)
  })
  it('the viewer page: the battle plays through — at the turn the unit is drawn and listed as its form, on the form\'s side, with the form\'s actions; at the revert as itself; seeking past and back lands on the same state', () => {
    const out = page('tools/plays-turned-units.test.mjs')
    expect(out).toMatch(/# pass 7/); expect(out).toMatch(/# fail 0/)
    for (const line of out.split('\n').filter((l) => /^# \\?# /.test(l))) console.log(line.replace(/^# \\?# /, '  '))
  }, 600000)
  it('the viewer page: the six opening recordings are the engine\'s own and the page plays every line of each (opening-replays), the first-affliction pop-up still stands (affliction-pop-up)', () => {
    for (const file of ['tools/opening-replays.test.mjs', 'tools/affliction-pop-up.test.mjs']) { const out = page(file); expect(out, file).toMatch(/# fail 0/); expect(out, file).not.toMatch(/# pass 0\b/) }
  }, 600000)
})
