// viewer.arrivals-camera (engine backlog; engine DECISIONS.md 2026-10-04 'the opening's tutorial: the first hero's class line,
// no map before battle 1, the Orphanage's lessons, the camera shows what arrives, new enemies are named, a closer start').
// Andrew: "Now we need a permanent feature: when a phase happens and enemies are introduced, the map is going to pan over to the
// enemies enough so they are on the screen. Don't center on them because they're usually on the edge and we don't want to go
// off the edge. For each side the enemies are on, we're going to go to that side. ... When we're done looking at the things
// that have been added, we're going to focus and center on the first hero that's activated."
// The engine's side — what the camera reads, and nothing new: a scheduled arrival is one encounter.wave line, then a unit.enter
// for each unit that names the encounter as how it arrived, at the Start of the Turn, before the Hero Phase and the first
// Activation (core/encounter.ts fireSchedule). The Orphanage's own waves come one a Turn (right edge, left edge, bottom); the
// page test's two-sided wave is the same encounter with its second and third waves fired together — made here by the engine
// and held as tools/fixtures/arrivals-two-sides.json. The viewer's half (../viewer/tools/arrivals-camera.test.mjs) plays both
// logs on the page; the sandbox's half (../kingdom/tools/arrivals-camera.verify.mjs) ends Turn 1 on the built
// BATTLE-SANDBOX.html and watches the view. Imports no page code.
//
//   ARRIVALS_WRITE=1 npm test -- viewer.arrivals-camera     rewrites the fixture from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createBattle } from '../../engine/src/core/setup.js'
import { runBattle } from '../../engine/src/core/battle.js'
import { scenarioDef, scenarioOptions } from '../../engine/src/content/scenarios.js'

const FIXTURE = 'tools/fixtures/arrivals-two-sides.json'
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x))
/** the Orphanage with its Turn 2 and Turn 3 arrivals (the right side, the left side) fired together at the Start of Turn 2 —
    each stood two columns in from its edge, at (17,5) and (2,6): hexes the camera can bring wholly inside its view. On the
    board's very first and last columns it cannot (viewer SWITCHES arrivalsEdgeColumn, a finding about the camera's bound) */
function twoSides() {
  const opts = scenarioOptions(scenarioDef('test.opening-orphanage'), 1), enc = opts.encounter!
  const [second, third, ...rest] = enc.schedule!
  const stood = (spawn: NonNullable<typeof second>['spawn'], col: number, row: number) => spawn!.map((x) => ({ ...x, at: { col, row } }))
  const encounter = { ...enc, schedule: [{ ...second!, spawn: [...stood(second!.spawn, 17, 5), ...stood(third!.spawn, 2, 6)] }, ...rest] }
  const ctx = createBattle({ ...opts, encounter })
  runBattle(ctx)
  /* through Turn 2 and no further: the wave, the first Activation after it, a little play */
  const end = ctx.events.findIndex((e) => e.type === 'turn.begin' && e.turn === 3)
  return { _about: 'GENERATED by test/viewer.arrivals-camera.test.ts (ARRIVALS_WRITE=1) from the engine — never hand-edit. The Orphanage (test.opening-orphanage, replicate 1) with its second and third scheduled arrivals fired together at the Start of Turn 2, each two columns in from its edge: a Zombie on the right side (17,5) and one on the left (2,6), in one wave. Events through the end of Turn 2.',
    seed: { mapId: opts.mapId, scenarioId: opts.scenarioId }, events: plain(ctx.events.slice(0, end < 0 ? ctx.events.length : end)) }
}

describe('the camera shows what arrives', () => {
  it('the engine: a scheduled arrival is an encounter.wave, then a unit.enter naming the encounter, before the Hero Phase\'s first Activation', () => {
    const opts = scenarioOptions(scenarioDef('test.opening-orphanage'), 1), ctx = createBattle(opts); runBattle(ctx)
    const EV = ctx.events, wave = EV.findIndex((e) => e.type === 'encounter.wave'), g = ctx.geo
    expect(EV[wave]).toMatchObject({ turn: 2, causeId: opts.encounter!.id })
    const enter = EV[wave + 1]!
    expect(enter).toMatchObject({ type: 'unit.enter', typeId: 'unit.zombie', arrived: opts.encounter!.id })
    expect(g.colOf(enter['hex'] as number)).toBe(g.board.width - 1)                      // the right edge
    const next = EV.slice(wave + 2).find((e) => e.type === 'phase.begin' || e.type === 'activation.begin')!
    expect(next.type).toBe('phase.begin'); expect(EV.slice(wave + 2).find((e) => e.type === 'activation.begin')!.phase).toBe('hero')
    // once the battle has begun, every unit that enters naming the encounter follows a wave line of the same Turn (a unit
    // raised or summoned by another unit's power names no encounter: it is not a wave)
    const begun = EV.findIndex((e) => e.type === 'battle.begin')
    const late = EV.filter((e, i) => i > begun && e.type === 'unit.enter' && e['arrived'])
    expect(late.length).toBeGreaterThan(1)
    for (const e of late) expect(EV.slice(begun, EV.indexOf(e)).some((w) => w.type === 'encounter.wave' && w.turn === e.turn)).toBe(true)
  })
  it('the fixture is the engine\'s: one wave on two sides — a Zombie at the right edge and one at the left, at the Start of Turn 2', () => {
    const now = twoSides()
    if (process.env.ARRIVALS_WRITE) writeFileSync(FIXTURE, JSON.stringify(now) + '\n')
    const held = JSON.parse(readFileSync(FIXTURE, 'utf8'))
    expect(held).toEqual(now)
    const EV = now.events, wave = EV.findIndex((e) => e.type === 'encounter.wave'), map = EV.find((e) => e.type === 'map.loaded')!, W = map['width'] as number
    const entered = EV.slice(wave + 1).filter((e) => e.type === 'unit.enter' && e.turn === 2 && e['arrived'])
    expect(entered.map((e) => (e['hex'] as number) % W).sort((a, b) => a - b)).toEqual([2, W - 3])
    expect(EV.filter((e) => e.type === 'encounter.wave' && e.turn === 2)).toHaveLength(1)
  })
  it('the viewer page: the view slides to each side\'s arrivals in turn, their drop-in plays while it is there, then it centres on the first hero', () => {
    const out = execFileSync(process.execPath, ['--test', '--test-reporter=tap', 'tools/arrivals-camera.test.mjs'], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 24, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })
    expect(out).toMatch(/# pass 5/); expect(out).toMatch(/# fail 0/)
  }, 170000)
  it('the sandbox: on the built BATTLE-SANDBOX.html (the Orphanage) — End Turn, and the view goes to the Zombie arriving at the right edge as far as the camera may, then to the first hero', () => {
    mkdirSync('../kingdom/scratch', { recursive: true })
    execFileSync(process.execPath, ['tools/build-sandbox.mjs', 'scratch/arrivals-camera.html'], { cwd: '../kingdom', stdio: 'pipe' })
    const out = execFileSync(process.execPath, ['tools/arrivals-camera.verify.mjs', 'scratch/arrivals-camera.html'], { cwd: '../kingdom', encoding: 'utf8', maxBuffer: 1 << 26 })
    expect(out).toMatch(/arrivals-camera: .*passed/)
  }, 170000)
})
