// viewer.attack-row-shows-totals (engine backlog; engine DECISIONS.md 2026-10-06 'an attack shows its total Accuracy and Crit, not
// the weapon's plus' and 'an attack's numbers: the total alone, no list of what it is made of'). Andrew: "In the attacks and
// actions, when you have a dagger, it shows +5 critical. It should not show the weapon modifier if the modifier is one of the
// stats that is regularly in use. Instead, that stat should be displayed. … The dagger doesn't show +5 critical. What happens is
// the attack shows the total critical. The same thing is true of accuracy. There's no reason to show a plus accuracy. You just
// put it in the accuracy." / "we should always be showing the numbers, not the contributing [sum] numbers. … We just need to see
// the total."
//
// The engine's side. The totals a row shows are the engine's own figure for the attacker's side of an attack before a target
// is chosen (engine core/pipeline.ts attackFigures — read-only, added for this item through the door). Held here:
//   · that figure is the pipeline's own: for every attack of every unit the six opening battles field, against every enemy
//     it could be aimed at, it is exactly the rows of the engine's Accuracy ledger that do not read the target, and its Crit
//     is the forecast's chance less what the target and the final Accuracy add;
//   · a Dagger's Stab carries its +5 in the Crit total and a Javelin's Throw its -10 in the Accuracy total;
//   · the fixture the page test reads (tools/fixtures/attack-totals.json) is the engine's own figures at the start of each of
//     the six opening recordings, line for line.
// The viewer's half (../viewer/tools/attack-row-shows-totals.test.mjs) reads the rows of the page; the kingdom's
// (../kingdom/tools/attack-row-shows-totals.verify.mjs) reads the built BATTLE-SANDBOX.html against the live engine.
//
//   ATTACK_TOTALS_WRITE=1 npm test -- viewer.attack-row-shows-totals     rewrites the fixture from the engine
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createBattle } from '../../engine/src/core/setup.js'
import { attackFigures, resolveAccuracy, preview, CRIT_BASE } from '../../engine/src/core/pipeline.js'
import { attacksOf } from '../../engine/src/core/action.js'
import { effective } from '../../engine/src/core/stats.js'
import { scenarioDef, scenarioOptions } from '../../engine/src/content/scenarios.js'
import type { Ctx, Unit } from '../../engine/src/core/types.js'

const FIXTURE = 'tools/fixtures/attack-totals.json'
const LIBRARY = JSON.parse(readFileSync('battles/library.json', 'utf8')).battles as { file: string; seed?: number }[]
const OPENINGS = LIBRARY.filter((b) => /^test\.opening-/.test(b.file)).map((b) => ({ scenario: b.file.replace(/\.json$/, ''), seed: b.seed ?? 0 }))
/** a recording's own fielding: the options its export states (its `seed`), so the battle made here is the battle recorded */
const fielded = (scenario: string, _seed: number): Ctx => createBattle(JSON.parse(readFileSync(`battles/${scenario}.json`, 'utf8')).seed as never)
void scenarioDef; void scenarioOptions
/** the rows of the engine's Accuracy ledger that read neither the target nor the way to it */
const OWN = new Set(['ADJACENT', 'ELEVATION', 'ATTACKER_PRONE', 'SITUATIONAL'])
function figuresNow() {
  type Row = { name: string; typeId: string; attacks: Record<string, { accuracy: number; crit: number; unlogged: { accuracy: number; crit: number } }> }
  const out: Record<string, Record<string, Row>> = {}
  /* what the engine counts into a figure with NO line of the log: an aura's lent modifier and the ground's (a tower, a wall) — both derived in the stat pipeline, never stored (stats.ts) —
     and for a ranged attack the height it is made from and an enemy beside it (the figure's own rows over the resolved stat) */
  const lent = (ctx: Ctx, u: Unit, stat: 'accuracy' | 'crit') => effective(ctx, u, stat).ledger.filter((r) => /^(aura|terrain)./.test(String(r.source))).reduce((n, r) => n + r.delta, 0)
  for (const { scenario, seed } of OPENINGS) {
    const ctx = fielded(scenario, seed), rows: Record<string, Row> = {}
    for (const u of ctx.state.units) { const mine: Row['attacks'] = {}
      for (const a of attacksOf(ctx, u)) { const f = attackFigures(ctx, u, a)
        mine[a.id] = { ...f, unlogged: { accuracy: lent(ctx, u, 'accuracy') + (f.accuracy - effective(ctx, u, 'accuracy').value - (a.attack.accuracy ?? 0)), crit: lent(ctx, u, 'crit') } } }
      rows[String(u.id)] = { name: u.name, typeId: u.typeId, attacks: mine } }
    out[scenario] = rows
  }
  return { _about: 'GENERATED by test/viewer.attack-row-shows-totals.test.ts (ATTACK_TOTALS_WRITE=1) from the engine — never hand-edit. For each of the six opening recordings, fielded from the recording\'s own options: unit id -> its name and type, the engine\'s own attackFigures for its every attack {accuracy, crit}, each with what of it the engine counts with no line of the log (unlogged: an aura\'s lent modifier; a ranged attack\'s ground).', figures: out }
}

describe('an attack\'s row shows its Accuracy and its Crit as totals: the engine\'s own figure', () => {
  it('the figure is the pipeline\'s: for every attack of every unit the six opening battles field, against every unit of the other side, it is the ledger\'s own rows that do not read the target, and its Crit is the forecast\'s less what the target and the final Accuracy add', () => {
    expect(OPENINGS.length).toBe(6)
    let asked = 0, withMod = 0
    for (const { scenario, seed } of OPENINGS) {
      const ctx = fielded(scenario, seed)
      for (const u of ctx.state.units) for (const a of attacksOf(ctx, u)) {
        const fig = attackFigures(ctx, u, a)
        if (a.attack.accuracy || a.attack.crit) withMod++
        for (const t of ctx.state.units.filter((x: Unit) => x.side !== u.side && x.lifeState === 'standing')) {
          const acc = resolveAccuracy(ctx, u, t, a)
          const own = effective(ctx, u, 'accuracy').value + acc.ledger.filter((r) => OWN.has(r.name)).reduce((n, r) => n + r.delta, 0)
          expect(fig.accuracy, `${scenario}: ${u.name}'s ${a.name} at ${t.name}`).toBe(own)
          const p = preview(ctx, u.id, t.id, a.id) as { accuracy: number; critChance: number }
          const surplus = p.accuracy > 100 ? Math.trunc((p.accuracy - 100) / 4) : 0, raw = CRIT_BASE + effective(ctx, u, 'crit').value + (a.attack.crit ?? 0)
          expect(fig.crit, `${scenario}: ${u.name}'s ${a.name}: Crit`).toBe(Math.max(0, raw))
          expect(p.critChance, `${scenario}: ${u.name}'s ${a.name} at ${t.name}: the forecast's Crit`).toBe(Math.max(0, raw + surplus - effective(ctx, t, 'luck').value))
          asked++
        }
      }
    }
    expect(asked).toBeGreaterThan(200); expect(withMod, 'attacks with a modifier of their own were among them').toBeGreaterThan(5)
    console.log(`  the engine: ${asked} attack-and-target pairs over the six opening battles; the row's figure was the ledger's own rows every time`)
  })
  it('a Dagger\'s Stab carries its +5 in the Crit total, a Javelin\'s Throw its -10 in the Accuracy total, and an attack with no modifier is the unit\'s own Accuracy and Crit', () => {
    const ctx = createBattle({ replicate: 0, mapId: 'map.open', heroes: ['hero.base.warrior-iron', 'hero.base.warrior-iron'], heroItems: [['item.dagger'], ['item.javelin']], enemies: ['unit.zombie'], enemyCount: 1 } as never)
    const [a, b] = ctx.state.units.filter((u: Unit) => u.side === 'hero')
    const unit = (u: Unit) => ({ accuracy: effective(ctx, u, 'accuracy').value, crit: CRIT_BASE + effective(ctx, u, 'crit').value })
    const stab = ctx.actions['attack.dagger.stab']!, thrown = ctx.actions['attack.javelin.throw']!
    expect(stab.attack!.crit).toBe(5); expect(thrown.attack!.accuracy).toBe(-10)
    expect(attackFigures(ctx, a!, stab as never)).toEqual({ accuracy: unit(a!).accuracy + (stab.attack!.accuracy ?? 0), crit: unit(a!).crit + 5 })
    expect(attackFigures(ctx, b!, thrown as never)).toEqual({ accuracy: unit(b!).accuracy - 10, crit: unit(b!).crit + (thrown.attack!.crit ?? 0) })
    // an attack with no modifier of its own: the Stab's row with its Crit and Accuracy taken off
    const plain = { ...stab, attack: { ...stab.attack!, crit: undefined, accuracy: undefined } }
    expect(attackFigures(ctx, b!, plain as never)).toEqual(unit(b!))
  })
  it('the fixture is the engine\'s own figures for the six opening recordings, line for line', () => {
    const now = figuresNow()
    if (process.env.ATTACK_TOTALS_WRITE) writeFileSync(FIXTURE, JSON.stringify(now) + '\n')
    expect(JSON.parse(readFileSync(FIXTURE, 'utf8')).figures).toEqual(now.figures)
  })
  it('the viewer page: each attack\'s row shows Accuracy then Crit as totals, the engine\'s figures where a host gives them; no row or tooltip names a part of a total', () => {
    const out = execFileSync(process.execPath, ['--test', '--test-reporter=tap', 'tools/attack-row-shows-totals.test.mjs'], { cwd: '../viewer', encoding: 'utf8', maxBuffer: 1 << 24, env: { ...process.env, VIEWER_PAGE: process.env.VIEWER_PAGE ?? '' } })
    expect(out).toMatch(/# pass 6/); expect(out).toMatch(/# fail 0/)
    for (const line of out.split('\n').filter((l) => /^# \\?# /.test(l))) console.log(line.replace(/^# \\?# /, '  '))
  }, 170000)
  it('the sandbox: on the built BATTLE-SANDBOX.html every attack row of the opening\'s heroes shows the live engine\'s Accuracy and Crit, and no "+5 Crit"; the Dagger\'s item card still says it', () => {
    mkdirSync('../kingdom/scratch', { recursive: true })
    execFileSync(process.execPath, ['tools/build-sandbox.mjs', 'scratch/attack-row-shows-totals.html'], { cwd: '../kingdom', stdio: 'pipe' })
    const out = execFileSync(process.execPath, ['tools/attack-row-shows-totals.verify.mjs', 'scratch/attack-row-shows-totals.html'], { cwd: '../kingdom', encoding: 'utf8', maxBuffer: 1 << 26 })
    expect(out).toMatch(/attack-row-shows-totals: .*passed/)
    for (const line of out.split('\n').filter((l) => /^  /.test(l))) console.log(line)
  }, 240000)
})
