// TEST BESTIARY — generated by content/mkbestiaryts.mjs from gen/bestiary-test.json.
// DO NOT EDIT BY HAND. Edit the JSON and regenerate.
//
// THROWAWAY BY DESIGN. Every id begins `test.`, every name begins "TEST — ".
// Delete this file and drop the spread from RAW_UNITS and nothing else changes.
// To promote one to real content: copy the row, drop the test marker, rename the id.
//
// Every one of these RUNS TODAY — nine hooks, three effect kinds, ten targeting
// shapes, all three damage types. What the engine cannot yet run is listed at the
// bottom of gen/bestiary-test.json and in BESTIARY-TEST.md.

import type { UnitDef } from '../core/types.js'

export const TEST_UNITS: Readonly<Record<string, UnitDef>> = {
  'test-rat': {
    // TESTS: The floor. Two health, nothing else — proves a kill resolves and a corpse leaves the
    // board.
    typeId: 'test-rat', side: 'enemy',
    maxHp: 2, armor: 0, resist: 0,
    accuracy: 60, dodge: 0, strength: 1, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 5, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [],
    ai: 'dumb-melee',
    attacks: ['attack.fangs.bite'],
    abilities: [],
    attributes: ['beast'],
  },
  'test-bruteling': {
    // TESTS: ARMOR. High Armor, zero Resist — physical damage should crawl and magic should not
    // care.
    typeId: 'test-bruteling', side: 'enemy',
    maxHp: 30, armor: 3, resist: 0,
    accuracy: 70, dodge: 0, strength: 6, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 3, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-wardling': {
    // TESTS: RESIST — the mirror of the Bruteling. Run the same two attacks at both and the
    // mitigation split has to show.
    typeId: 'test-wardling', side: 'enemy',
    maxHp: 20, armor: 0, resist: 3,
    accuracy: 70, dodge: 0, strength: 4, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['demon'],
  },
  'test-flicker': {
    // TESTS: DODGE, and the onDodge predicate when it is built: 40 Dodge means misses that are
    // dodges, not misses that are bad rolls.
    typeId: 'test-flicker', side: 'enemy',
    maxHp: 8, armor: 0, resist: 0,
    accuracy: 70, dodge: 40, strength: 3, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 6, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [],
    ai: 'melee-aggressive',
    attacks: ['attack.fangs.bite'],
    abilities: [],
    attributes: ['demon'],
  },
  'test-truebearer': {
    // TESTS: REACH and the ranged accuracy stations — -5 a hex past the first, and -20 if it fires
    // while something is adjacent to it.
    typeId: 'test-truebearer', side: 'enemy',
    maxHp: 10, armor: 0, resist: 0,
    accuracy: 75, dodge: 0, strength: 0, precision: 4, magic: 0, spirit: 0,
    role: 'ranged',
    movement: 4, reach: 5,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [],
    ai: 'ranged-kite',
    attacks: ['attack.ranger.bow'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-swinger': {
    // TESTS: onAttack — fires on EVERY swing, hit or miss. If Protection climbs on a miss, the hook
    // is on the right rung.
    typeId: 'test-swinger', side: 'enemy',
    maxHp: 12, armor: 1, resist: 0,
    accuracy: 70, dodge: 0, strength: 4, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.swinger.wind-up', hook: 'onAttack', chance: 100,
        select: 'self',
        effect: { kind: 'status.apply', statusId: 'status.protection', value: 1 },
        source: 'test.unit.swinger',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-flailer': {
    // TESTS: onMiss — and deliberately 40 Accuracy so it misses often enough to see. It hurts itself
    // when it whiffs.
    typeId: 'test-flailer', side: 'enemy',
    maxHp: 12, armor: 0, resist: 0,
    accuracy: 40, dodge: 0, strength: 5, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.flailer.overswing', hook: 'onMiss', chance: 100,
        select: 'self',
        effect: { kind: 'damage', amount: 1, damageType: 'true' },
        source: 'test.unit.flailer',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-critter': {
    // TESTS: onCrit, and the crit formula itself. 130 Accuracy is 30 surplus, which is (130-100)/4 =
    // +7 Crit. If it never crits, the surplus is being clamped.
    typeId: 'test-critter', side: 'enemy',
    maxHp: 14, armor: 0, resist: 0,
    accuracy: 130, dodge: 0, strength: 3, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 5, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.critter.taste', hook: 'onCrit', chance: 100,
        select: 'target',
        effect: { kind: 'status.apply', statusId: 'status.bleed', value: 2 },
        source: 'test.unit.critter',
      },
    ],
    ai: 'melee-aggressive',
    attacks: ['attack.fangs.bite'],
    abilities: [],
    attributes: ['undead', 'vampire'],
  },
  'test-devourer': {
    // TESTS: onKill — the KILLER’s hook. Pair it with the Rat so a kill is easy to force.
    typeId: 'test-devourer', side: 'enemy',
    maxHp: 18, armor: 1, resist: 0,
    accuracy: 75, dodge: 0, strength: 5, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 5, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.devourer.feed', hook: 'onKill', chance: 100,
        select: 'self',
        effect: { kind: 'status.apply', statusId: 'status.regeneration', value: 3 },
        source: 'test.unit.devourer',
      },
    ],
    ai: 'melee-aggressive',
    attacks: ['attack.fangs.bite'],
    abilities: [],
    attributes: ['beast', 'werewolf'],
  },
  'test-thornback': {
    // TESTS: onTakingDamage — the VICTIM’s hook, so its "target" is whoever swung. This is Thorns,
    // and it should reach a ranged attacker too.
    typeId: 'test-thornback', side: 'enemy',
    maxHp: 16, armor: 2, resist: 0,
    accuracy: 65, dodge: 0, strength: 3, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 3, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.thornback.spines', hook: 'onTakingDamage', chance: 100,
        select: 'target',
        effect: { kind: 'damage', amount: 2, damageType: 'true' },
        source: 'test.unit.thornback',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['undead', 'construct'],
  },
  'test-bloatling': {
    // TESTS: onDeath, AND that it fires from Settle rather than from the attack — kill it with a
    // Poison tick and the burst must still happen. Also the first area-origin-self trigger.
    typeId: 'test-bloatling', side: 'enemy',
    maxHp: 6, armor: 0, resist: 0,
    accuracy: 60, dodge: 0, strength: 2, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.bloatling.burst', hook: 'onDeath', chance: 100,
        select: { select: 'area', side: 'any', radius: 1, origin: 'self' },
        effect: { kind: 'damage', amount: 3, damageType: 'magic' },
        source: 'test.unit.bloatling',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-pacer': {
    // TESTS: onActivationEnd, NOT turnEnd. On an eight-unit board this must fire eight times a Turn,
    // not once.
    typeId: 'test-pacer', side: 'enemy',
    maxHp: 10, armor: 0, resist: 0,
    accuracy: 65, dodge: 0, strength: 3, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.pacer.settle', hook: 'onActivationEnd', chance: 100,
        select: 'self',
        effect: { kind: 'status.apply', statusId: 'status.protection', value: 1 },
        source: 'test.unit.pacer',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-gravecaller': {
    // TESTS: THE HEAL-ALL-ZOMBIES AURA. Area + side:ally + requireTags:[undead] + radius 3. Put one
    // live zombie and one Rat (beast) inside it — the Rat must get nothing. Standing auras do not
    // exist yet, so this fires at end of activation instead; see the note below.
    typeId: 'test-gravecaller', side: 'enemy',
    maxHp: 14, armor: 0, resist: 1,
    accuracy: 70, dodge: 0, strength: 0, precision: 2, magic: 3, spirit: 0,
    role: 'support',
    movement: 4, reach: 3,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.gravecaller.grave-tide', hook: 'onActivationEnd', chance: 100,
        select: { select: 'area', side: 'ally', radius: 3, origin: 'self', requireTags: ['undead'] },
        effect: { kind: 'status.apply', statusId: 'status.regeneration', value: 2 },
        source: 'test.unit.gravecaller',
      },
    ],
    ai: 'ranged-kite',
    attacks: ['attack.mage.staff'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-dreadbrand': {
    // TESTS: THE DAMAGE-ALL-HEROES AURA. Area + side:enemy + radius 2. Every hero inside takes 2
    // magic; nothing enemy-side does. Walk a hero in and out to see the boundary.
    typeId: 'test-dreadbrand', side: 'enemy',
    maxHp: 16, armor: 1, resist: 1,
    accuracy: 70, dodge: 0, strength: 3, precision: 0, magic: 0, spirit: 0,
    role: 'support',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.dreadbrand.dread', hook: 'onActivationEnd', chance: 100,
        select: { select: 'area', side: 'enemy', radius: 2, origin: 'self' },
        effect: { kind: 'damage', amount: 2, damageType: 'magic' },
        source: 'test.unit.dreadbrand',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['demon'],
  },
  'test-hellsherald': {
    // TESTS: side:any — the aura that hits enemies, allies AND itself. The actor is always one of
    // its own allies, by ruling, so it must Weak itself too.
    typeId: 'test-hellsherald', side: 'enemy',
    maxHp: 12, armor: 0, resist: 2,
    accuracy: 70, dodge: 0, strength: 2, precision: 0, magic: 0, spirit: 0,
    role: 'support',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.hellsherald.everyone', hook: 'onActivationEnd', chance: 100,
        select: { select: 'area', side: 'any', radius: 2, origin: 'self' },
        effect: { kind: 'status.apply', statusId: 'status.weak', value: 1 },
        source: 'test.unit.hellsherald',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['demon'],
  },
  'test-plaguebell': {
    // TESTS: AREA WITH NO RADIUS — the unbounded form, "every hero on the board". Distance must not
    // be consulted at all.
    typeId: 'test-plaguebell', side: 'enemy',
    maxHp: 12, armor: 0, resist: 0,
    accuracy: 70, dodge: 0, strength: 0, precision: 2, magic: 0, spirit: 0,
    role: 'support',
    movement: 4, reach: 3,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.plaguebell.toll', hook: 'onActivationEnd', chance: 100,
        select: { select: 'area', side: 'enemy' },
        effect: { kind: 'status.apply', statusId: 'status.poison', value: 1 },
        source: 'test.unit.plaguebell',
      },
    ],
    ai: 'ranged-kite',
    attacks: ['attack.mage.staff'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-cleanser': {
    // TESTS: status.remove — the only effect kind nothing else here exercises. Set its friends on
    // fire and watch it put them out.
    typeId: 'test-cleanser', side: 'enemy',
    maxHp: 12, armor: 0, resist: 1,
    accuracy: 70, dodge: 0, strength: 0, precision: 2, magic: 0, spirit: 2,
    role: 'support',
    movement: 4, reach: 3,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.cleanser.scour', hook: 'onActivationEnd', chance: 100,
        select: { select: 'area', side: 'ally', radius: 2, origin: 'self' },
        effect: { kind: 'status.remove', statusId: 'status.burn' },
        source: 'test.unit.cleanser',
      },
    ],
    ai: 'ranged-kite',
    attacks: ['attack.mage.staff'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-channeler': {
    // TESTS: ValueSpec SCALING — partyMagic, the SIDE-WIDE sum, not this unit’s own Magic. Field it
    // alone, then field it beside another Magic user; the number has to move.
    typeId: 'test-channeler', side: 'enemy',
    maxHp: 12, armor: 0, resist: 1,
    accuracy: 75, dodge: 0, strength: 0, precision: 2, magic: 4, spirit: 0,
    role: 'ranged',
    movement: 4, reach: 4,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.channeler.draw', hook: 'onHit', chance: 100,
        select: 'target',
        effect: { kind: 'damage', amount: { scale: 'partyMagic', mult: 1, div: 2, base: 1, round: 'down' }, damageType: 'magic' },
        source: 'test.unit.channeler',
      },
    ],
    ai: 'ranged-kite',
    attacks: ['attack.mage.strike'],
    abilities: [],
    attributes: ['demon'],
  },
  'test-coinflip': {
    // TESTS: CHANCE, and two triggers on the SAME hook from the same source. Both must roll on their
    // own named stream — about a quarter of hits should land both.
    typeId: 'test-coinflip', side: 'enemy',
    maxHp: 10, armor: 0, resist: 0,
    accuracy: 70, dodge: 0, strength: 3, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.coinflip.a', hook: 'onDamage', chance: 50,
        select: 'target',
        effect: { kind: 'status.apply', statusId: 'status.stun', value: 1 },
        source: 'test.unit.coinflip',
      },
      {
        id: 'test.trigger.coinflip.b', hook: 'onDamage', chance: 50,
        select: 'target',
        effect: { kind: 'status.apply', statusId: 'status.slow', value: 1 },
        source: 'test.unit.coinflip',
      },
    ],
    ai: 'dumb-melee',
    attacks: ['attack.zombie.basic'],
    abilities: [],
    attributes: ['demon'],
  },
  'test-cleaver': {
    // TESTS: origin:’target’ — the cleave. The radius is measured from the thing it just hit, not
    // from itself. This is the pair to the Bloatling’s origin:self.
    typeId: 'test-cleaver', side: 'enemy',
    maxHp: 18, armor: 1, resist: 0,
    accuracy: 70, dodge: 0, strength: 5, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 4, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.cleaver.follow-through', hook: 'onHit', chance: 100,
        select: { select: 'area', side: 'enemy', radius: 1, origin: 'target' },
        effect: { kind: 'damage', amount: 2, damageType: 'physical' },
        source: 'test.unit.cleaver',
      },
    ],
    ai: 'melee-aggressive',
    attacks: ['attack.warrior.axe'],
    abilities: [],
    attributes: ['undead'],
  },
  'test-hunter': {
    // TESTS: requireTags as a FILTER on an enemy-side area. Field it against a mixed hero party plus
    // a raised skeleton and only the undead should take it.
    typeId: 'test-hunter', side: 'enemy',
    maxHp: 16, armor: 0, resist: 0,
    accuracy: 75, dodge: 10, strength: 4, precision: 0, magic: 0, spirit: 0,
    role: 'melee',
    movement: 6, reach: 0,
    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina
    triggers: [
      {
        id: 'test.trigger.hunter.mark-the-dead', hook: 'onHit', chance: 100,
        select: { select: 'area', side: 'enemy', radius: 2, origin: 'self', requireTags: ['undead'] },
        effect: { kind: 'damage', amount: 2, damageType: 'true' },
        source: 'test.unit.hunter',
      },
    ],
    ai: 'melee-aggressive',
    attacks: ['attack.fangs.bite'],
    abilities: [],
    attributes: ['beast'],
  },
}

/** Not runnable yet — each names the engine capability it is waiting on. */
export const TEST_UNITS_BLOCKED = [
  // TEST — Standing Aura (BLOCKED)
  // NEEDS: the `aura` hook — a standing property with a radius, checked continuously
  // Every aura above is faked as onActivationEnd, so it pulses once per activation instead of
  // being TRUE while you stand there. A hero who walks in and out mid-activation is untouched. 28
  // content entries carry a real aura; this is the gap.
  'test.unit.standing-aura',
  // TEST — Opener (BLOCKED)
  // NEEDS: the `startOfBattle` hook
  // 36 content entries fire at startOfBattle. Nothing enemy-side can currently deploy, buff
  // itself, or summon on turn zero.
  'test.unit.opener',
  // TEST — Riposte (BLOCKED)
  // NEEDS: the `onDodge` hook
  // Fires on the DEFENDER when its Dodge is why the attack missed. The Flicker at 40 Dodge is the
  // fixture waiting for it. See engine/COMBAT-SEQUENCE.md #onDodge.
  'test.unit.riposte',
  // TEST — Slayer (BLOCKED)
  // NEEDS: damage station 400 VS_TARGET
  // "+2 damage against undead" cannot be expressed. 43 content entries need it. See
  // engine/COMBAT-SEQUENCE.md #Conditional-on-the-target.
  'test.unit.slayer',
  // TEST — Brood (BLOCKED)
  // NEEDS: summoning, and rule.summon-order
  // A unit that puts two more units on the board, each with its own stat block and AI, acting
  // first in summon order.
  'test.unit.brood',
  // TEST — Groundskeeper (BLOCKED)
  // NEEDS: ground layers as a persistent tile state
  // TERRAIN.BURNING and TERRAIN.POISONED exist as constants in types.ts and nothing writes them. A
  // hex that is set burning must still be burning next Turn.
  'test.unit.groundskeeper',
  // TEST — Frostbite (BLOCKED)
  // NEEDS: status.frost
  // Frost is one of the ten authored statuses and `src/content/statuses.ts` does not define it.
  // Same for status.karma.
  'test.unit.frostbite',
] as const
