// mkbestiaryts.mjs — emit the test bestiary as engine-ready TypeScript.
// Source of truth is gen/bestiary-test.json; this is a projection of it, never edited by hand.
//   node mkbestiaryts.mjs   ->  bestiary-test.ts
// Paste the UNITS object into engine/src/content/index.ts's RAW_UNITS, or import it.
import fs from 'fs';
const B=JSON.parse(fs.readFileSync('gen/bestiary-test.json','utf8'));
const q=s=>"'"+String(s).replace(/'/g,"\\'")+"'";
const sel=t=>typeof t==='string' ? q(t)
  : '{ select: '+q(t.select)+', side: '+q(t.side)
    +(t.radius!==undefined?', radius: '+t.radius:'')
    +(t.origin?', origin: '+q(t.origin):'')
    +(t.requireTags?', requireTags: ['+t.requireTags.map(q).join(', ')+']':'')+' }';
const val=v=>typeof v==='object'
  ? '{ scale: '+q(v.scale)+(v.mult!==undefined?', mult: '+v.mult:'')+(v.div!==undefined?', div: '+v.div:'')
    +(v.base!==undefined?', base: '+v.base:'')+(v.round?', round: '+q(v.round):'')+' }' : String(v);
const eff=e=>e.kind==='status.apply' ? "{ kind: 'status.apply', statusId: "+q(e.statusId)+", value: "+val(e.value)+" }"
  : e.kind==='status.remove' ? "{ kind: 'status.remove', statusId: "+q(e.statusId)+" }"
  : "{ kind: 'damage', amount: "+val(e.amount)+", damageType: "+q(e.damageType)+" }";
const wrap=(s,n=94,pad='      ')=>{const w=s.split(' ');const out=[];let l='';
  for(const x of w){ if((l+' '+x).length>n){out.push(l);l=x} else l=l?l+' '+x:x } if(l)out.push(l);
  return out.map(x=>pad+'// '+x).join('\n')};
const L=[];
L.push('// TEST BESTIARY — generated by content/mkbestiaryts.mjs from gen/bestiary-test.json.');
L.push('// DO NOT EDIT BY HAND. Edit the JSON and regenerate.');
L.push('//');
L.push('// THROWAWAY BY DESIGN. Every id begins `test.`, every name begins "TEST — ".');
L.push('// Delete this file and drop the spread from RAW_UNITS and nothing else changes.');
L.push('// To promote one to real content: copy the row, drop the test marker, rename the id.');
L.push('//');
L.push('// Every one of these RUNS TODAY — nine hooks, three effect kinds, ten targeting');
L.push('// shapes, all three damage types. What the engine cannot yet run is listed at the');
L.push('// bottom of gen/bestiary-test.json and in BESTIARY-TEST.md.');
L.push('');
L.push("import type { UnitDef } from '../core/types.js'");
L.push('');
L.push('export const TEST_UNITS: Readonly<Record<string, UnitDef>> = {');
for(const u of B.units){
  const key=u.id.replace(/^test\.unit\./,'test-');
  const s=u.stats;
  L.push('  '+q(key).replace(/'/g,"'")+': {');
  L.push(wrap('TESTS: '+u.tests,94,'    '));
  L.push('    typeId: '+q(key)+', side: '+q('enemy')+',');
  L.push('    maxHp: '+s.maxHp+', armor: '+s.armor+', resist: '+s.resist+',');
  L.push('    accuracy: '+s.accuracy+', dodge: '+s.dodge+', strength: '+s.strength
        +', precision: '+s.precision+', magic: '+s.magic+', spirit: '+s.spirit+',');
  L.push('    role: '+q(u.role)+',');
  L.push('    movement: '+s.movement+', reach: '+s.reach+',');
  L.push('    maxStamina: 0, staminaRegen: 0,   // enemies do not run stamina');
  if((u.triggers||[]).length){
    L.push('    triggers: [');
    for(const t of u.triggers){
      L.push('      {');
      L.push('        id: '+q(t.id)+', hook: '+q(t.hook)+', chance: '+t.chance+',');
      L.push('        select: '+sel(t.select)+',');
      L.push('        effect: '+eff(t.effect)+',');
      L.push('        source: '+q(u.id)+',');
      L.push('      },');
    }
    L.push('    ],');
  } else L.push('    triggers: [],');
  L.push('    ai: '+q(u.ai)+',');
  L.push('    attacks: ['+(u.attacks||[]).map(q).join(', ')+'],');
  L.push('    abilities: [],');
  L.push('    attributes: ['+(u.tags||[]).map(q).join(', ')+'],');
  L.push('  },');
}
L.push('}');
L.push('');
L.push('/** Not runnable yet — each names the engine capability it is waiting on. */');
L.push('export const TEST_UNITS_BLOCKED = [');
for(const b of B.blocked){
  L.push('  // '+b.name);
  L.push(wrap('NEEDS: '+b.needs,94,'  '));
  L.push(wrap(b.why,94,'  '));
  L.push('  '+q(b.id)+',');
}
L.push('] as const');
L.push('');
fs.writeFileSync('bestiary-test.ts',L.join('\n'));
console.log('bestiary-test.ts  '+L.length+' lines, '+B.units.length+' units, '+B.blocked.length+' blocked');
