// mkenginepack.mjs — export the TEST COHORT as the engine's generated unit pack.
// Run AFTER assemble.mjs. Writes ../engine/src/content/generated/pack.ts.
//
// Ruled 2026-08-20: "we're going to read from the data and it's clearly
// differentiated text. We're not hardcoding." The engine's standard battle
// party and enemies come from HERE — the Codex pipeline — not from hand-typed
// rows. Deterministic output: same inputs, byte-identical pack.
import fs from 'fs';
const D = JSON.parse(fs.readFileSync('hbt-content.json', 'utf8'));
if (!D.testCohort) { console.error('mkenginepack: no testCohort in hbt-content.json — run assemble.mjs first.'); process.exit(1); }

const ACTION = { applyPoison: 'status.poison', applyBleed: 'status.bleed', applyBurn: 'status.burn' };
const TARGET = { attacked: 'target', self: 'self' };
const HOOKS = new Set(['onAttack', 'onMiss', 'onHit', 'onCrit', 'onDamage', 'onKill', 'onTakingDamage', 'onDeath', 'onActivationEnd']);
const dropped = [];

function mapCodexTriggers(h, typeId) {
  const out = [];
  for (const [hook, rows] of Object.entries(h.triggers || {})) {
    for (const r of rows || []) {
      const statusId = ACTION[r.action];
      const select = TARGET[r.target];
      if (!HOOKS.has(hook) || !statusId || !select) {
        dropped.push(`${typeId}: ${hook}/${r.action} -> no engine meaning yet`);
        continue;
      }
      const t = {
        id: 'test.' + typeId.replace(/^test-/, '') + '.' + r.action.replace(/([A-Z])/g, '-$1').toLowerCase(),
        hook, chance: 100, select,
        effect: { kind: 'status.apply', statusId, value: r.value ?? 1 },
        source: 'unit.' + typeId,
      };
      if (r.onlyWithAttack) t.onlyWithAttack = r.onlyWithAttack;
      out.push(t);
    }
  }
  return out;
}

const heroes = D.testCohort.heroes.map((h) => {
  const p = h.ported || {}, d = h.derivedBase || {}, e = h.engine || {};
  return {
    typeId: h.typeId, name: h.name, side: 'hero', copyOf: h.copyOf,
    maxHp: p.health, armor: p.armor ?? 0, resist: p.resist ?? 0,
    accuracy: d.accuracy, dodge: p.dodge ?? 0,
    strength: p.strength ?? 0, precision: p.precision ?? 0, magic: p.magic ?? 0, spirit: p.spirit ?? 0,
    role: e.role, movement: d.movement, reach: p.reach ?? 0,
    maxStamina: d.staminaMax, staminaRegen: d.staminaRegen ?? 1,
    ai: e.ai, attacks: e.attacks || [], abilities: e.abilities || [],
    // Movement is a granted CHOICE (ruled 2026-08-21) — no default here: a
    // cohort row without moves should fail the loader, loudly.
    moves: e.moves,
    attributes: ['hero-test'],
    triggers: [...mapCodexTriggers(h, h.typeId), ...(e.riders || [])],
  };
});
const enemies = D.testCohort.enemies.map((z) => { const { copyOf, ...row } = z; return { ...row, side: 'enemy', copyOf }; });

const pack = { note: D.testCohort.note, heroes, enemies };
const body = '// GENERATED by content/mkenginepack.mjs — NEVER HAND-EDIT (see engine CLAUDE.md,\n'
  + '// "Never hand-edit anything under generated/"). Source of truth: the Codex\n'
  + '// pipeline (content/settled.json testCohort -> hbt-content.json).\n'
  + '// Regenerate:  cd content && node assemble.mjs && node mkenginepack.mjs\n'
  + (dropped.length ? '// Dropped (no engine meaning yet): ' + dropped.join(' | ') + '\n' : '')
  + 'export const UNIT_PACK = ' + JSON.stringify(pack, null, 2) + ' as const\n';
fs.writeFileSync('../engine/src/content/generated/pack.ts', body);
console.log(`pack.ts: ${heroes.length} heroes, ${enemies.length} enemies${dropped.length ? ', dropped: ' + dropped.length : ''}`);
