// mkgaps.mjs — regenerate ../CONTENT-GAPS.md from what the pipeline actually found.
//
// CONTENT-GAPS.md is listed under "never hand-edit" and has said "Generated. Do not hand-edit."
// since it was written — but nothing generated it. It sat unchanged from 2026-08-09 holding
// worked EXAMPLES (badge.bloodscent, badge.mourner) that were never real rows. A file that
// claims to be generated and is not is worse than no file: it is read as a report.
//
// Run it last, after assemble + mkbestiary:
//   node mkgaps.mjs
//
// The four categories come from CLAUDE.md and they have four different fixes:
//   1 missing content     — author it, no permission needed
//   2 missing capability  — STOP. Do not build a hook so one row fits.
//   3 missing station     — STOP. Constitution-relevant.
//   4 ambiguity           — engine/SWITCHES.md, and let a sweep answer it

import fs from 'fs';

const D = JSON.parse(fs.readFileSync('hbt-content.json', 'utf8'));
const read = p => { try { return fs.readFileSync(p, 'utf8'); } catch { return ''; } };

// ---- category 2: everything the port could not say in the closed vocabulary
const bestiaryGaps = read('gen/bestiary-gaps.txt').split('\n').filter(Boolean);
// Group by REASON, so the report reads as "here are the things the engine cannot say" rather
// than as a list of creatures. Two line shapes exist: "Who: verb — why" from a mapped action,
// and "Who: prose — why" from a whole-card finding (transformation, onEnter). The first parser
// only knew the former and dumped 43 real findings into an "unparsed" bucket, which is exactly
// the kind of quiet miscategorisation that made CONTENT-GAPS worthless the first time.
const byReason = new Map();
const put = (key, who) => { if (!byReason.has(key)) byReason.set(key, []); byReason.get(key).push(who); };
for (const line of bestiaryGaps) {
  const m = line.match(/^(.*?): (.*?) — (.*)$/);
  if (!m) { put('could not be parsed — fix mkgaps.mjs', line); continue; }
  const [, who, what, why] = m;
  // Normalise the whole-card findings so eight identical transformations are one entry, not
  // eight, and every dropped onEnter counts under the same heading.
  let key;
  if (/^transforms into/.test(what))        key = `transformation — ${why}`;
  else if (/onEnter effect\(s\) dropped/.test(what)) key = `onEnter triggers — ${why}`;
  else if (/^createAura inside a trigger/.test(what)) key = `createAura in a trigger — ${why}`;
  else if (/^fastAttack/.test(what))        key = `fastAttack — ${why}`;
  else key = `${what.split('/').pop()} — ${why}`;
  put(key, who);
}

// ---- category 1: ids referenced by something that owns no row of their own
const ids = new Set();
for (const k of ['items','attacks','powers','enchants','specialties','badges','classes','tags'])
  for (const e of (D[k] || [])) if (e && e.id) ids.add(e.id);
for (const u of (D.bestiary || [])) { ids.add(u.id); for (const a of (u.attacks||[])) ids.add(a.id); }
const dangling = [];
for (const i of (D.items || [])) for (const g of (i.grants || [])) if (!ids.has(g)) dangling.push(`item ${i.id} grants ${g}`);
for (const s of (D.specialties || [])) for (const p of (s.powers || [])) if (!ids.has(p)) dangling.push(`specialty ${s.id} lists ${p}`);

// ---- category 4: what is deliberately unanswered
const switches = read('../engine/SWITCHES.md');
const openSwitches = (switches.match(/^###?\s+/gm) || []).length;

const L = [];
const P = s => L.push(s);

P('# Gaps');
P('');
P('**Generated by `content/mkgaps.mjs`. Do not hand-edit — rerun it.**');
P('');
P(`Regenerated ${new Date().toISOString().slice(0,10)} from the live pipeline.`);
P('');
P('What the content demands that the engine cannot yet express. Four categories, because');
P('they have four different fixes and only two of them are safe to act on alone.');
P('');
P('| | Category | Fix |');
P('|---|---|---|');
P(`| 1 | Missing content | ${dangling.length} — author it |`);
P(`| 2 | Missing capability | ${bestiaryGaps.length} — **stop and report** |`);
P('| 3 | Missing station | 0 — **stop and report** |');
P(`| 4 | Ambiguity | ${openSwitches} in engine/SWITCHES.md |`);
P('');
P('---');
P('');
P('## 1. Missing content — automatic');
P('');
P('Rows that reference an id with no definition. These are content, and content is cheap.');
P('');
if (!dangling.length) P('*None. Every referenced id resolves.*');
else dangling.forEach(d => P(`- ${d}`));
P('');
P('## 2. Missing capability — **stop here**');
P('');
P('The engine has no hook, no effect, no way to say this. **A hook is not invented so that');
P('one row fits** — that bespoke-hook failure is the thing this project exists to prevent.');
P('These rows are left unconverted and named, not quietly reshaped until they build.');
P('');
if (!bestiaryGaps.length) P('*None.*');
else for (const [reason, who] of [...byReason.entries()].sort((a,b) => b[1].length - a[1].length)) {
  P(`### \`${reason}\``);
  P('');
  P(`**${who.length} abilities** need this:`);
  P('');
  const shown = who.slice(0, 12);
  shown.forEach(w => P(`- ${w}`));
  if (who.length > shown.length) P(`- *…and ${who.length - shown.length} more*`);
  P('');
}
P('## 3. Missing station — **stop here**');
P('');
P('Content that needs a new point in the combat sequence to fire at. Constitution-relevant:');
P('adding one changes the order of operations for everything.');
P('');
P('*None found.*');
P('');
P('## 4. Ambiguity — a switch, not a decision');
P('');
P('A rule that could reasonably go two ways is not decided here. It becomes a switch with a');
P('question and a default, and a sweep answers it. Adding a switch is always better than');
P('guessing.');
P('');
P(openSwitches ? `See \`engine/SWITCHES.md\` — ${openSwitches} recorded.` : '*No switches file found.*');
P('');

fs.writeFileSync('../CONTENT-GAPS.md', L.join('\n'));
console.log(`../CONTENT-GAPS.md regenerated`);
console.log(`  1 missing content    : ${dangling.length}`);
console.log(`  2 missing capability : ${bestiaryGaps.length}  (${byReason.size} distinct)`);
console.log(`  3 missing station    : 0`);
console.log(`  4 ambiguity          : ${openSwitches}`);
