// map.caravan-aftermath (engine backlog encounter.caravan-aftermath, 2026-10-01): battle maps compiled straight from a
// painted 3D scene's MEASURED navigation (assets/terrain-3d/<scene>/navigation.json — the cells the scene was measured
// on, its sceneSha256 the scene's), for a scene that has no Ground Check letter grid (mkopeningmaps.mjs is that path).
// ONE compile path for every such scene; SCENES names them.
//
//   navigation cell usable      '.'  open ground
//   navigation cell not usable  'x'  the engine's high obstacle (open ground plus a high material-3 prop): a wreck the
//                                    measure found solid, and a standing pocket walled off by wreckage (engine SWITCHES.md
//                                    caravanBlocked) — both are physical obstruction, never a place to stand or path
//   cursedCells                 the scene's corpse hexes — cursed ground, painted by the encounter as layer.weak
//                                (DECISIONS.md 2026-09-28 "cursed ground is layer.weak"; 2026-10-01 the caravan's fight)
//   groundFireCells             the scene's ground fires — burning ground, painted by the encounter as layer.burning
//                                (cart fires on wrecks stand on 'x' hexes and stay decorative)
// The lists are the scene's, read here and carried as `ground`; an encounter names them (`"paint": [{"layer":
// "layer.weak", "ground": "cursed"}]`) and never retypes the hexes — resolvePaint fills them in for assemble and the
// pack alike.
//
//   node mkpaintedmaps.mjs            write gen/painted-maps.json
//   node mkpaintedmaps.mjs --check    exit 1 if gen/painted-maps.json is stale
import fs from 'node:fs';
import { compileMaps } from './map-schema.mjs';

const OUT = 'gen/painted-maps.json';
export const SCENES = [
  { scene: 'caravan-aftermath', id: 'map.caravan-aftermath', name: 'Caravan Aftermath' },
];
/** the ground lists a scene's navigation carries, by the name an encounter's paint uses */
const GROUND = { cursed: 'cursedCells', fire: 'groundFireCells' };

export function compileScene({ scene, id, name }, nav = JSON.parse(fs.readFileSync(`../assets/terrain-3d/${scene}/navigation.json`, 'utf8'))) {
  if (!nav.checks?.passed) throw new Error(`${id}: ${scene}/navigation.json has not passed its checks`);
  const { cols, rows, cells } = nav;
  if (!Number.isSafeInteger(cols) || !Number.isSafeInteger(rows) || cells.length !== cols * rows) throw new Error(`${id}: navigation is not ${cols}x${rows}`);
  const out = [];
  for (let r = 0; r < rows; r++) {
    let line = '';
    for (let c = 0; c < cols; c++) {
      const cell = cells[r * cols + c];
      if (cell.id !== r * cols + c || cell.col !== c || cell.row !== r) throw new Error(`${id}: navigation cell ${r * cols + c} is (${cell.col},${cell.row})`);
      line += cell.usable ? '.' : 'x';
    }
    out.push(line);
  }
  const ground = {};
  for (const [key, field] of Object.entries(GROUND)) {
    const hexes = nav[field];
    if (!Array.isArray(hexes)) throw new Error(`${id}: navigation carries no ${field}`);
    for (const h of hexes) if (!Number.isSafeInteger(h) || !cells[h]?.usable) throw new Error(`${id}: ${field} hex ${h} is not a usable cell — ground is painted where a unit can stand`);
    ground[key] = [...hexes].sort((a, b) => a - b);
  }
  const note = `${name}, ${cols}x${rows}. Compiled by content/mkpaintedmaps.mjs from the measured navigation of assets/terrain-3d/${scene} (scene ${nav.sceneSha256.slice(0, 12)}): ${cells.filter((x) => x.usable).length} usable hexes open, the rest high obstacles; ${ground.cursed.length} cursed and ${ground.fire.length} burning hexes for the encounter to paint.`;
  return { row: { id, name, note, rows: out, panel: false }, ground, sceneSha256: nav.sceneSha256 };
}

export function buildPaintedMaps() {
  const maps = [], ground = {}, scenes = {};
  for (const s of SCENES) { const { row, ground: g, sceneSha256 } = compileScene(s); maps.push(row); ground[row.id] = g; scenes[row.id] = { scene: s.scene, sceneSha256 } }
  compileMaps(maps); // the same schema the pack compiles with — refuse here, not later
  return {
    _note: 'GENERATED by content/mkpaintedmaps.mjs from assets/terrain-3d/<scene>/navigation.json — never hand-edit; re-run it. assemble.mjs appends `maps` to the shipping lane; `ground` is each map\'s cursed and burning hexes (row x width + col) for its encounter\'s paint to name (resolvePaint).',
    maps, ground, scenes,
  };
}

/** an encounter row's paint with every `ground` reference filled in from its map's ground lists (a paint that lists
    its hexes is left as it is). Refuses a reference to ground the map does not carry. */
export function resolvePaint(row, painted) {
  if (!Array.isArray(row.paint)) return row.paint;
  return row.paint.map((p) => {
    if (p.ground === undefined) return p;
    if (p.hexes !== undefined) throw new Error(`encounters ${row.id}: a paint names its hexes or its map's ground, never both`);
    const hexes = painted?.ground?.[row.map]?.[p.ground];
    if (!hexes) throw new Error(`encounters ${row.id}: map ${row.map} carries no '${p.ground}' ground (gen/painted-maps.json)`);
    const { ground: _g, ...rest } = p;
    return { ...rest, hexes: [...hexes] };
  });
}
export const readPainted = () => (fs.existsSync(OUT) ? JSON.parse(fs.readFileSync(OUT, 'utf8')) : null);

if (process.argv[1]?.endsWith('mkpaintedmaps.mjs')) {
  const text = JSON.stringify(buildPaintedMaps(), null, 1) + '\n';
  if (process.argv.includes('--check')) {
    const now = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (now !== text) { console.error(`${OUT} is stale — run node mkpaintedmaps.mjs`); process.exit(1); }
    console.log(`${OUT} current`);
  } else { fs.writeFileSync(OUT, text); console.log(`wrote ${OUT}`); }
}
