#!/usr/bin/env python3
"""build-hex-art.py — hex battle-token art for codex heroes.

Sibling of build-hero-art.py / build-bestiary-art.py, and follows their conventions
exactly: md5(src)[:12].webp keys, one manifest keyed by codex id, regenerable.

  reads   ../art/manifest.json       codex id -> {thumb, src}   (generated, never edited)
          hex-map.json               codex id -> token slug     (authored by hand)
          ../../battle-tokens/units/ <slug>_{full,1024,256}.png

  writes  ../art/hex/<hash>.webp     280px, ALPHA PRESERVED
          ../art/hex-manifest.json   codex id -> {hex, src, slug, scale, tiers}

Why a separate manifest rather than a `hex` field on art/manifest.json: that file is
generated by build-hero-art.py, so anything added by hand there is destroyed on the next
run. bestiary-manifest.json already establishes the sibling pattern.

Alpha is the entire point of a battle token, so thumbnails are RGBA webp. Do not convert
to RGB "to match the hero thumbs" — that fills the cutout with black.
"""
import hashlib, json, os, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CONT = os.path.dirname(HERE)
ART = os.path.join(CONT, 'art')
HEXDIR = os.path.join(ART, 'hex')
UNITS = os.path.abspath(os.path.join(CONT, '..', 'battle-tokens', 'units'))
WIDTH = 280

try:
    from PIL import Image
except ImportError:
    sys.exit('pillow required: pip install pillow')


def main():
    hero = json.load(open(os.path.join(ART, 'manifest.json')))
    hexmap = json.load(open(os.path.join(HERE, 'hex-map.json')))
    os.makedirs(HEXDIR, exist_ok=True)

    out, missing = {}, []
    for hid, ent in hexmap.items():
        slug = ent['slug'] if isinstance(ent, dict) else ent
        scale = ent.get('scale', 1.0) if isinstance(ent, dict) else 1.0
        if hid not in hero:
            missing.append((hid, 'not in art/manifest.json')); continue
        src = hero[hid]['src']
        full = os.path.join(UNITS, f'{slug}_full.png')
        if not os.path.exists(full):
            missing.append((hid, f'no token at {full}')); continue

        key = hashlib.md5(src.encode()).hexdigest()[:12] + '.webp'
        im = Image.open(full).convert('RGBA')
        h = round(im.height * WIDTH / im.width)
        im.resize((WIDTH, h), Image.LANCZOS).save(
            os.path.join(HEXDIR, key), 'WEBP', quality=90, lossless=False)

        out[hid] = {
            'hex': key, 'src': src, 'slug': slug,
            # Advisory stature, NOT baked into the pixels. Tokens export at a uniform
            # height, which throws stature away; this puts it back at render time.
            'scale': scale,
            'tiers': {t: f'{slug}_{t}.png' for t in ('full', '1024', '256')},
        }

    json.dump(out, open(os.path.join(ART, 'hex-manifest.json'), 'w'), indent=1)
    print(f'hex art: {len(out)} tokens -> art/hex/ + art/hex-manifest.json')
    for hid, why in missing:
        print(f'  SKIP {hid}: {why}')
    return 0 if not missing else 1


if __name__ == '__main__':
    sys.exit(main())
