#!/usr/bin/env python3
"""build-status-hex-art.py — hex battle-token art for the four affliction statuses.

Sibling of build-hex-art.py, and follows it exactly: md5(src)[:12].webp keys, one
manifest keyed by codex id, regenerable, alpha preserved.

  reads   ../art/manifest.json          codex id -> {thumb, src}   (generated, never edited)
          status-hex-map.json           codex id -> hero token slug (authored by hand)
          ../../battle-tokens/units/    <slug>-<status>_{full,1024,256}.png
          ../../art/heroes/<slug>/card/<status>.<ext>   the source the token was cut from

  writes  ../art/status-hex/<hash>.webp     280px, ALPHA PRESERVED
          ../art/status-hex-manifest.json   "<codexId>.<status>" -> {hex, src, slug, status, scale, tiers}

WHY A SIBLING MANIFEST AND NOT A FIELD ON art/manifest.json. Same reason
bestiary-hex-manifest.json exists: art/manifest.json is generated by build-hero-art.py
from hell-tcg's base card art and carries no status axis at all (297 keys, none of them
a status). Anything added there by hand is destroyed on the next run of that script.

The map is keyed by the codex id of the hero's CHARACTER 1, because that is the
character every status card was painted from -- exactly as the base hex tokens were.
"""
import hashlib, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CONT = os.path.dirname(HERE)
ROOT = os.path.dirname(CONT)
ART = os.path.join(CONT, 'art')
HEXDIR = os.path.join(ART, 'status-hex')
UNITS = os.path.join(ROOT, 'battle-tokens', 'units')
WIDTH = 280
STATUSES = ['vampirism', 'lycanthropy', 'possession', 'rotting-flesh']

try:
    from PIL import Image
except ImportError:
    sys.exit('pillow required: pip install pillow')


def card_src(slug, status):
    for e in ('png', 'jpg', 'jpeg'):
        p = os.path.join(ROOT, 'art', 'heroes', slug, 'card', f'{status}.{e}')
        if os.path.exists(p):
            return f'art/heroes/{slug}/card/{status}.{e}'
    return None


def main():
    hero = json.load(open(os.path.join(ART, 'manifest.json')))
    hexmap = json.load(open(os.path.join(HERE, 'status-hex-map.json')))
    os.makedirs(HEXDIR, exist_ok=True)

    out, missing = {}, []
    for hid, ent in hexmap.items():
        slug = ent['slug'] if isinstance(ent, dict) else ent
        scale = ent.get('scale', 1.0) if isinstance(ent, dict) else 1.0
        if hid not in hero:
            missing.append((hid, 'not in art/manifest.json')); continue
        for status in STATUSES:
            key_id = f'{hid}.{status}'
            src = card_src(slug, status)
            if not src:
                missing.append((key_id, 'no status card art on disk')); continue
            full = os.path.join(UNITS, f'{slug}-{status}_full.png')
            if not os.path.exists(full):
                missing.append((key_id, f'no token at {full}')); continue

            key = hashlib.md5(src.encode()).hexdigest()[:12] + '.webp'
            im = Image.open(full).convert('RGBA')
            h = round(im.height * WIDTH / im.width)
            im.resize((WIDTH, h), Image.LANCZOS).save(
                os.path.join(HEXDIR, key), 'WEBP', quality=90, lossless=False)

            out[key_id] = {
                'hex': key, 'src': src, 'slug': slug, 'status': status,
                # Advisory stature, NOT baked into the pixels -- same contract as
                # hex-manifest.json: tokens export at a uniform height, this puts
                # the real stature back at render time.
                'scale': scale,
                'tiers': {t: f'{slug}-{status}_{t}.png' for t in ('full', '1024', '256')},
            }

    json.dump(out, open(os.path.join(ART, 'status-hex-manifest.json'), 'w'), indent=1)
    print(f'status hex art: {len(out)} tokens -> art/status-hex/ + art/status-hex-manifest.json')
    for hid, why in missing:
        print(f'  SKIP {hid}: {why}')
    return 0 if not missing else 1


if __name__ == '__main__':
    sys.exit(main())
