// Items — the kingdom's registry over the engine's compiled rows. GEAR-DESIGN.md §1–§4.
//
// kingdom.reads-engine (2026-10-02; engine DECISIONS.md "the duplication review, ruled", findings K2 K8 K11): an
// item's battle facts — class, tier, hands, slots, restriction, the stats it folds (in the engine's stat names), what
// it grants, the uses its powers carry, and every Forge-derived row — are the ENGINE's rows, read through the door.
// The kingdom kept its own copy of every row, built by the same rules, and the copies disagreed. What the engine does
// not carry is the campaign's and is GENERATED (src/content/generated/items.ts, by tools/mk-items.mjs from the codex):
// tags and sets, the set bonus, the Waystation band and price, the equip cost, and the codex stat words that are
// campaign quantities (itemSlots). A Forge or tier-3 row takes its base's campaign fields (and its enchant's campaign
// stats). Nothing here is typed by hand; this file joins the two and gives the lookups.

import { ITEM_CAMPAIGN_ROWS, ENCHANT_CAMPAIGN_ROWS } from './generated/items.js'
import { omitDisabled } from './disable.js'
import { ITEMS as ENGINE_ITEMS, ACTIONS, usesPerBattleOf, type ItemDef } from '../engine.js'

export type ItemClass = ItemDef['itemClass']

/** What the campaign knows of a codex item that the engine does not — generated by tools/mk-items.mjs. */
export type CampaignItemRow = {
  readonly id: string
  readonly tags: readonly string[]
  readonly sets: readonly string[]
  readonly setBonus: ItemRow['setBonus']
  readonly waystationBand: number | null
  readonly price: Readonly<Record<string, number>>
  readonly equipCost: Readonly<Record<string, number>>
  /** The codex's authored uses — read only where the engine names this row's uses a gap (no power compiled to carry them). */
  readonly uses: number | null
  /** Codex stat words the engine has no stat for — campaign quantities (itemSlots, corruption), keyed by the word. */
  readonly campaignMods: Readonly<Record<string, number>>
}
export type CampaignEnchantRow = { readonly id: string; readonly campaignMods: Readonly<Record<string, number>> }

export type ItemRow = {
  readonly id: string
  readonly name: string
  readonly itemClass: ItemClass
  /** 0 junk · 1 starting and the Forge's shelf · 2 masterwork and buyable enchants · 3 rewards · 4–6 the trade-in. GEAR-DESIGN.md §2. */
  readonly tier: number
  /** Hands a weapon or shield takes: 1 or 2 — a two-hander fills both. An item worn from its own slot takes none (the engine's handsOf). */
  readonly hands: number
  /** Item slots it costs when carried in the general slots. Armor is 0: it has its own slot. */
  readonly slots: number
  readonly classRestriction: string | null
  readonly tags: readonly string[]
  /** The set TAGS this item is a member of — its tags that some codex setBonus names (GEAR-DESIGN.md §5, resolved 2026-09-03: a set is a tag, not a kind). An item may carry several. */
  readonly sets: readonly string[]
  /**
   * The bonus THIS item pays for members of a set, or null. Two shapes (GEAR-DESIGN.md §5):
   * per-other — `each` per OTHER equipped member of `tag`; at-count — `once`, paid once when
   * `at` members are worn, this item included. Keys are the engine's stat names, or `attackDamage` for
   * this weapon's own attacks; the battle receives them as heroMods.
   */
  readonly setBonus: { readonly tag: string; readonly each?: Readonly<Record<string, number>>; readonly withItself?: true; readonly at?: number; readonly once?: Readonly<Record<string, number>> } | null
  /** Uses per battle for a one-use item, restocked after; null = permanent. The engine's (its powers' uses). */
  readonly uses: number | null
  /** The Waystation band that opens this row in its catalog, or null — it is not sold there. */
  readonly waystationBand: number | null
  /** What the Waystation charges, by currency id. Empty when it does not sell it. */
  readonly price: Readonly<Record<string, number>>
  /** What equipping costs, by currency id: idols Faith, Bloodrunes Mana, nothing else. */
  readonly equipCost: Readonly<Record<string, number>>
  /** The stats it folds onto the hero, in the engine's names (the engine's row), plus the campaign's own quantities (itemSlots). */
  readonly statModifiers: Readonly<Record<string, number>>
  /** The attacks and powers the item grants — the engine reads these; the kingdom only carries them. */
  readonly grants: readonly string[]
  /** For a derived row: the tier-1 base and the enchant it carries. */
  readonly base: string | null
  readonly enchant: string | null
  readonly source: 'codex' | 'masterwork' | 'enchanted' | 'combination'
}

const CAMPAIGN: ReadonlyMap<string, CampaignItemRow> = new Map(ITEM_CAMPAIGN_ROWS.map((r) => [r.id, r]))
const ENCHANT_CAMPAIGN: ReadonlyMap<string, CampaignEnchantRow> = new Map(ENCHANT_CAMPAIGN_ROWS.map((r) => [r.id, r]))

/**
 * The uses a row has per battle: its powers' (the engine's usesPerBattleOf). Where the engine names the row's uses a
 * gap — a one-use codex row whose power is not compiled yet (capability.consumables) — the codex's authored count stands
 * in, so the Waystation still sells and restocks it as one-use (kingdom SWITCHES.md itemUsesUncompiled). Loud when the
 * two disagree.
 */
function usesOf(e: ItemDef, own: CampaignItemRow): number | null {
  const engine = usesPerBattleOf(e, ACTIONS)
  if (engine !== null) {
    if (own.id === e.id && own.uses !== null && own.uses !== engine) throw new Error(`item '${e.id}': the codex says ${own.uses} uses, the engine's powers carry ${engine} — one owner`)
    return engine
  }
  return own.id === e.id && (e.gaps ?? []).some((g) => g.startsWith('uses:')) ? own.uses : null
}

const sortedMods = (o: Readonly<Record<string, number>>): Record<string, number> =>
  Object.fromEntries(Object.keys(o).sort().filter((k) => o[k] !== 0).map((k) => [k, o[k]!]))

/** One engine row joined to its campaign fields — the base's for a Forge or tier-3 row. */
function rowOf(e: ItemDef & { readonly base?: string; readonly enchant?: string }): ItemRow {
  const own = CAMPAIGN.get(e.id) ?? (e.base ? CAMPAIGN.get(e.base) : undefined)
  if (!own) throw new Error(`item '${e.id}': no campaign fields — neither it nor its base is a codex item (src/content/generated/items.ts)`)
  const mods: Record<string, number> = { ...e.statModifiers }
  for (const extra of [own.campaignMods, e.enchant ? ENCHANT_CAMPAIGN.get(e.enchant)?.campaignMods ?? {} : {}]) {
    for (const [k, v] of Object.entries(extra)) mods[k] = (mods[k] ?? 0) + v
  }
  return {
    id: e.id, name: e.name, itemClass: e.itemClass, tier: e.tier, hands: e.hands, slots: e.slots,
    classRestriction: e.classRestriction ?? null,
    tags: own.tags, sets: own.sets, setBonus: own.setBonus, uses: usesOf(e, own),
    waystationBand: own.waystationBand, price: own.price, equipCost: own.equipCost,
    statModifiers: sortedMods(mods), grants: [...e.grants, ...e.abilities],
    base: e.base ?? null, enchant: e.enchant ?? null,
    source: !e.base ? 'codex' : !e.enchant ? 'masterwork' : e.tier >= 3 ? 'combination' : 'enchanted',
  }
}

const ENGINE_ROWS = ENGINE_ITEMS as Readonly<Record<string, ItemDef & { readonly base?: string; readonly enchant?: string }>>
export const ITEMS: readonly ItemRow[] = omitDisabled(Object.keys(ENGINE_ROWS).sort().map((id) => rowOf(ENGINE_ROWS[id]!)))

const BY_ID: ReadonlyMap<string, ItemRow> = new Map(ITEMS.map((r) => [r.id, r]))

export function itemOf(id: string): ItemRow {
  const row = BY_ID.get(id)
  if (!row) throw new Error(`unknown item '${id}' — items are the engine's compiled rows joined to the codex's campaign fields (${ITEMS.length} of them)`)
  return row
}

/** The engine's own row for an item — what its hands are counted from (loadout.ts). */
export function engineItemOf(id: string): ItemDef {
  const row = ENGINE_ROWS[id]
  if (!row) throw new Error(`unknown item '${id}' — not an engine item row`)
  return row
}

// V2 R1 (2026-09-23): itemClass 'shield' is the shield class; the older tag-only shields
// (holy-shield — itemClass weapon, left as authored; pot-lid was the other until it was cut, 2026-10-03) still read as shields here.
export const isShield = (r: ItemRow): boolean => r.itemClass === 'shield' || r.tags.includes('shield')
export const isWeapon = (r: ItemRow): boolean => r.itemClass === 'weapon' && !isShield(r)
