import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto'
import {createBattle} from '../src/core/setup.js';import {advanceBattle,completeActionCycle,runBattle} from '../src/core/battle.js';import {runActivation} from '../src/ai/modes.js';import {movementOptions,nearestEnemy,movePowerOf} from '../src/core/movement.js';import {forkBattle} from '../src/core/fork.js';import {MAP_PANEL} from '../src/content/maps.js';import {battleCursorCases} from '../test/battle-cursor-cases.js'
function verifyChoice(row:any,before:any[],after:any[]){
 const i=before.findIndex((e,j)=>JSON.stringify(e)!==JSON.stringify(after[j]));assert.ok(i>=0,'must contain a first divergence');const a=before[i],b=after[i]
 assert.equal(a.type,'move.begin');assert.equal(b.type,'move.begin');assert.equal(a.actor,row.actor);assert.equal(b.actor,row.actor);assert.equal(a.causeId,b.causeId)
 assert.equal(a.from,row.from);assert.equal(b.from,row.from);assert.equal(a.to,row.old.hex);assert.equal(b.to,row.best.hex)
 assert.equal(a.hexes,row.old.path.length);assert.equal(b.hexes,row.best.path.length)
 assert.deepEqual(before.slice(0,i),after.slice(0,i));return i
}
if(process.argv.includes('--verify-report')){const report=JSON.parse(fs.readFileSync('scratch/contact-transition-comparison.json','utf8'));for(const row of report.changes)verifyChoice(row,row.before,row.after);console.log(`Verified actual first divergent move.begin actor/from/to/path length for all ${report.changes.length} changed battles.`);process.exit(0)}
const base='4ff6e55',temporary=fs.mkdtempSync(path.join(os.tmpdir(),'hobat-contact-before-')),hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex')
try{
 for(const file of execFileSync('git',['ls-tree','-r','--name-only',base,'src'],{encoding:'utf8'}).trim().split(/\r?\n/)){const target=path.resolve(temporary,file);assert.ok(target.startsWith(temporary+path.sep));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,execFileSync('git',['show',`${base}:${file}`],{maxBuffer:16*1024*1024}))}
 fs.writeFileSync(path.join(temporary,'package.json'),'{"type":"module"}')
 const load=(f:string)=>import(pathToFileURL(path.join(temporary,f)).href),oldBattle=await load('src/core/battle.ts'),oldAi=await load('src/ai/modes.ts')
 const cases=[...MAP_PANEL.flatMap(mapId=>Array.from({length:25},(_,replicate)=>({id:mapId+'/'+replicate,create:()=>createBattle({mapId,replicate,enemyCount:8,strict:true})}))),...battleCursorCases(),...['priory','angled-halls','buried-pilgrimage'].map(name=>({id:'atlas/'+name,create:()=>createBattle(JSON.parse(fs.readFileSync('../assets/battle-atlas/generated-combat/showcase.atlas-'+name+'.json','utf8')).atlasSetup)}))]
 const changed:any[]=[],unchanged:string[]=[],current:any[]=[]
 for(const fixture of cases){const before=fixture.create(),after=forkBattle(before);after.events=structuredClone(before.events);let first:any=null
  for(let guard=0;guard<10000;guard++){const a=oldBattle.advanceBattle(before),b=advanceBattle(after);assert.deepEqual(b,a,fixture.id+' lifecycle before first choice');if(a.kind==='complete')break
   assert.deepEqual(after.state,before.state);assert.deepEqual(after.rng,before.rng);const u=after.state.units[a.actor]!,target=nearestEnemy(after,u),power=movePowerOf(after,u,'path');let evidence:any=null
   if(u.ai==='dumb-melee'&&target&&power){const d0=after.geo.distance(u.hex,target.hex),plans=movementOptions(after,u.id,power.id).filter(p=>after.geo.distance(p.destination,target.hex)<d0),old=[...plans].sort((x,y)=>after.geo.distance(x.destination,target.hex)-after.geo.distance(y.destination,target.hex)||x.destination-y.destination)[0],best=[...plans].sort((x,y)=>after.geo.distance(x.destination,target.hex)-after.geo.distance(y.destination,target.hex)||x.pathCost-y.pathCost||x.path.length-y.path.length||x.destination-y.destination)[0];if(old&&best&&old.destination!==best.destination)evidence={turn:after.state.turn,actor:a.actor,mode:u.ai,target:target.id,from:u.hex,distance:after.geo.distance(best.destination,target.hex),old:{hex:old.destination,cost:old.pathCost,path:old.path},best:{hex:best.destination,cost:best.pathCost,path:best.path}}}
   const at=before.events.length;oldAi.runActivation(before,a.actor);runActivation(after,b.actor)
   if(JSON.stringify(before.events)!==JSON.stringify(after.events)){assert.ok(evidence,fixture.id+' first difference must be exactly a contact tie');assert.ok(evidence.best.cost<evidence.old.cost||(evidence.best.cost===evidence.old.cost&&evidence.best.path.length<evidence.old.path.length));const difference=verifyChoice(evidence,before.events.slice(at),after.events.slice(at));first={...evidence,firstDivergence:difference,before:before.events.slice(at,at+8),after:after.events.slice(at,at+8)};oldBattle.completeActionCycle(before);completeActionCycle(after);break}
   oldBattle.completeActionCycle(before);completeActionCycle(after);if(guard===9999)throw Error('comparison guard exceeded')
  }
  const priorResult=oldBattle.runBattle(before),result=runBattle(after)
  if(!first){assert.deepEqual(after.events,before.events);assert.deepEqual(after.state,before.state);assert.deepEqual(after.rng,before.rng);assert.deepEqual(after.battleCursor,before.battleCursor);assert.deepEqual(result,priorResult);unchanged.push(fixture.id)}else changed.push({id:fixture.id,...first,resultChanged:JSON.stringify(result)!==JSON.stringify(priorResult)})
  if(battleCursorCases().some(f=>f.id===fixture.id))current.push({id:fixture.id,changed:!!first,events:hash(after.events),state:hash(after.state),rng:hash(after.rng.log),result})
 }
 const report={base,battles:cases.length,changed:changed.length,unchanged:unchanged.length,resultChanges:changed.filter(c=>c.resultChanged).length,unchangedIds:unchanged,changes:changed}
 fs.writeFileSync('scratch/contact-transition-comparison.json',JSON.stringify(report,null,2)+'\n');const frozen=JSON.stringify({sourceCommit:base,workingTreeChange:'fix.ai-melee-contact',rulesVersion:'v2-migration.15',cases:current},null,2)+'\n';if(fs.existsSync('test/fixtures/battle-cursor-contact.json'))assert.equal(fs.readFileSync('test/fixtures/battle-cursor-contact.json','utf8').replace(/\r\n/g,'\n'),frozen);else fs.writeFileSync('test/fixtures/battle-cursor-contact.json',frozen,{flag:'wx'});console.log(JSON.stringify({base,battles:cases.length,changed:changed.length,unchanged:unchanged.length,resultChanges:report.resultChanges,cursorChanges:current.filter(c=>c.changed).map(c=>c.id)}))
}finally{assert.equal(path.dirname(temporary),path.resolve(os.tmpdir()));assert.ok(path.basename(temporary).startsWith('hobat-contact-before-'));fs.rmSync(temporary,{recursive:true,force:true})}
