import '../../engine/tools/engine-modules.mjs'   // first: links engine/node_modules into a worker's copy (Andrew, 2026-10-01)
import {readFileSync,writeFileSync,existsSync} from 'node:fs'
import {execFileSync} from 'node:child_process'
import {codeStamp} from '../../engine/tools/code-stamp.mjs'
import {createRequire} from 'node:module'
import {battleViewAssets,scopeBattleCSS} from './battle-view-assets.mjs'
const require=createRequire(import.meta.url),esbuild=require('../../engine/node_modules/esbuild'),postcss=require('../../engine/node_modules/postcss')
const sha=execFileSync('git',['rev-parse','--short','HEAD'],{encoding:'utf8'}).trim()
/* the engine's code stamp, not its HEAD (Andrew, 2026-10-01) */
const provenance=(({stamp,dirty})=>({engineCommit:stamp,engineDirty:dirty}))(codeStamp())
// viewer.play-input: the playable screen's battles stand on their painted scenes with their 3D models — the viewer's own
// packs (viewer.painted-board, viewer.character-models), handed to the component as data like every other table
const {packPaintedScenes}=await import('../../viewer/tools/painted-scenes.mjs'),{packCharacterModels}=await import('../../viewer/tools/character-models.mjs')
const data={...battleViewAssets(),paintedScenes:packPaintedScenes(),characterModels:await packCharacterModels()}
/* kingdom.opening-loop-three: the ?map sitting's after-battle screens (ui/after.ts) play the kingdom art they play in
   SLICE.html — the heroes' portraits, the sounds, the reward card back, the fonts — inlined as tools/build-slice.mjs inlines
   them; the map and town pictures are SLICE's alone. Absent art is not an error: the screens draw without it */
const art=(()=>{
 if(!existsSync('generated/art/index.json'))return null
 const index=JSON.parse(readFileSync('generated/art/index.json','utf8')),keep={heroes:index.heroes,audio:index.audio,cardBack:index.cardBack,fonts:index.fonts}
 const files=new Set([...Object.values(keep.heroes??{}),...Object.values(keep.audio??{}).map(a=>a.file),...(keep.cardBack?[keep.cardBack]:[]),...Object.keys(keep.fonts??{})]),inlined={}
 for(const name of [...files].sort()){const mime=name.endsWith('.png')?'image/png':name.endsWith('.woff2')?'font/woff2':name.endsWith('.mp3')?'audio/mpeg':'image/jpeg';inlined[name]=`data:${mime};base64,${readFileSync('generated/art/'+name).toString('base64')}`}
 return {...keep,data:inlined}
})()
/* the sitting's draft and Equip screens wear the slice's own styles (slice.css), scoped under .sliceView so the sandbox
   and the battle keep theirs */
function sliceScoped(source){
 const root=postcss.parse(source)
 root.walkRules(rule=>{for(let p=rule.parent;p;p=p.parent)if(p.type==='atrule'&&/keyframes$/i.test(p.name))return
  rule.selectors=rule.selectors.map(sel=>[':root','html','body','#app'].includes(sel)?'.sliceView':'.sliceView '+sel)})
 return root.toString()
}
const result=esbuild.buildSync({entryPoints:['src/ui/sandbox.ts'],nodePaths:['../viewer/node_modules'],bundle:true,platform:'browser',format:'iife',target:['es2022'],write:false,legalComments:'none',define:{__ART__:JSON.stringify(art),__BUILD_SHA__:JSON.stringify(sha),__ENGINE_PROVENANCE__:JSON.stringify(provenance),__BATTLE_VIEW_DATA__:JSON.stringify(data)}})
const shared=readFileSync('../viewer/src/styles.css','utf8').replace(/url\(["']?art\/([^"')]+)["']?\)/g,(_,file)=>{if(!data.assets[file])throw Error('Missing viewer CSS art '+file);return `url("${data.assets[file]}")`})
const css=readFileSync('src/ui/sandbox.css','utf8')+'\n'+sliceScoped(readFileSync('src/ui/slice.css','utf8'))+'\n'+readFileSync('src/ui/after.css','utf8')+'\n'+scopeBattleCSS(shared)
const js=('/*! Three.js\n'+readFileSync('../viewer/node_modules/three/LICENSE','utf8')+'\n*/\n'+result.outputFiles[0].text).replace(/<\/script/g,'<\\/script')
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>HoBaT Battle Sandbox</title><!-- Generated by tools/build-sandbox.mjs; kingdom ${sha}; engine ${provenance.engineCommit}${provenance.engineDirty?' dirty':''} --><style>${css}</style></head><body><div id="app"></div><script>${js}</script></body></html>`
const out=process.argv[2]??'BATTLE-SANDBOX.html';writeFileSync(out,html);console.log(`${out}: ${Buffer.byteLength(html)} bytes; kingdom ${sha}; engine ${provenance.engineCommit}`)
