import {readFileSync,writeFileSync} from 'node:fs'
import {execFileSync} from 'node:child_process'
import {createRequire} from 'node:module'
import {battleViewAssets,scopeBattleCSS} from './battle-view-assets.mjs'
const require=createRequire(import.meta.url),esbuild=require('../../engine/node_modules/esbuild')
const sha=execFileSync('git',['rev-parse','--short','HEAD'],{encoding:'utf8'}).trim()
const provenance={engineCommit:execFileSync('git',['-C','../engine','rev-parse','--short','HEAD'],{encoding:'utf8'}).trim(),engineDirty:!!execFileSync('git',['-C','../engine','status','--porcelain'],{encoding:'utf8'}).trim()}
const data=battleViewAssets()
const result=esbuild.buildSync({entryPoints:['src/ui/sandbox.ts'],nodePaths:['../viewer/node_modules'],bundle:true,platform:'browser',format:'iife',target:['es2022'],write:false,legalComments:'none',define:{__BUILD_SHA__:JSON.stringify(sha),__ENGINE_PROVENANCE__:JSON.stringify(provenance),__BATTLE_VIEW_DATA__:JSON.stringify(data)}})
const shared=readFileSync('../viewer/src/styles.css','utf8').replace(/url\(["']?art\/([^"')]+)["']?\)/g,(_,file)=>{if(!data.assets[file])throw Error('Missing viewer CSS art '+file);return `url("${data.assets[file]}")`})
const css=readFileSync('src/ui/sandbox.css','utf8')+'\n'+scopeBattleCSS(shared)
const js=('/*! Three.js\n'+readFileSync('../viewer/node_modules/three/LICENSE','utf8')+'\n*/\n'+result.outputFiles[0].text).replace(/<\/script/g,'<\\/script')
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>HoBaT Battle Sandbox</title><!-- Generated by tools/build-sandbox.mjs; kingdom ${sha}; engine ${provenance.engineCommit}${provenance.engineDirty?' dirty':''} --><style>${css}</style></head><body><div id="app"></div><script>${js}</script></body></html>`
const out=process.argv[2]??'BATTLE-SANDBOX.html';writeFileSync(out,html);console.log(`${out}: ${Buffer.byteLength(html)} bytes; kingdom ${sha}; engine ${provenance.engineCommit}`)
