#!/usr/bin/env node
// Builds SLICE.html — the slice's screens as ONE self-contained page, the
// project's BATTLE-VIEWER / GAME-BUILDER pattern (ruled 2026-09-01). esbuild
// comes from engine/node_modules (it ships with vitest); the bundle is inlined,
// the fixture is inlined, and the page works by double-click, offline.
//
//   node tools/build-slice.mjs
//
// Generated output. Never hand-edit SLICE.html — change src/ui and rebuild.

import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { execSync } from 'node:child_process'

const require = createRequire(import.meta.url)
const esbuild = require('../../engine/node_modules/esbuild')

const fixture = readFileSync('fixtures/slice-prep.json', 'utf8')
const sha = (() => { try { return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim() } catch { return 'unknown' } })()

const { outputFiles, warnings } = esbuild.buildSync({
  entryPoints: ['src/ui/slice.ts'],
  bundle: true,
  format: 'iife',
  target: ['es2022'],
  platform: 'browser',
  write: false,
  minify: false,
  legalComments: 'none',
  define: { __FIXTURE_JSON__: JSON.stringify(fixture), __BUILD_SHA__: JSON.stringify(sha) },
  logLevel: 'warning',
})
for (const w of warnings) console.warn(w.text)
const js = outputFiles[0].text.replace(/<\/script/g, '<\\/script')
const css = readFileSync('src/ui/slice.css', 'utf8')

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HoBaT — the slice</title>
<!-- GENERATED by kingdom/tools/build-slice.mjs at kingdom ${sha}. Never hand-edit. -->
<style>
${css}
</style>
</head>
<body>
<div id="app"></div>
<script>
${js}
</script>
</body>
</html>
`
writeFileSync('SLICE.html', html)
console.log(`SLICE.html — ${(html.length / 1024).toFixed(0)} KB, kingdom ${sha}`)
