#!/usr/bin/env node
// The recap's hero quotes, taken from Hell-TCG's data/combatQuotes.js — the victory and
// defeat banks by outcome and by class. Ruled 2026-09-04 (Angela): the after-battle
// screens are copied from Hell-TCG; the quote is part of the recap. HoBaT's heroes carry
// no personality field yet, so only the CLASS pools apply (the 30% path of getQuote);
// the personality pools are carried along so they light up the day a hero has one.
//
//   node tools/mk-quotes.mjs [--hell ../../hell-tcg]
//
// Writes src/content/generated/quotes.ts. Never hand-edit; regenerate.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { resolve } from 'node:path'

const argv = process.argv.slice(2)
const val = (f, d) => { const i = argv.indexOf(f); return i >= 0 ? argv[i + 1] : d }
const HELL = val('--hell', '../../hell-tcg')
const src = resolve(HELL, 'data/combatQuotes.js')
const mod = await import(pathToFileURL(src).href)
const { VICTORY_QUOTES, DEFEAT_QUOTES } = mod

/** Hell-TCG class names → HoBaT class ids, where a class exists on both sides. */
const CLASS = { Warrior: 'class.warrior', Rogue: 'class.rogue', Mage: 'class.mage', Ranger: 'class.ranger', Priest: 'class.priest', Paladin: 'class.paladin' }
const byClass = (bank) => Object.fromEntries(Object.entries(bank.class).filter(([k]) => CLASS[k]).map(([k, v]) => [CLASS[k], v]))
const out = {
  victory: { outcomes: Object.keys(VICTORY_QUOTES.personality.grim ?? {}), personality: VICTORY_QUOTES.personality, class: byClass(VICTORY_QUOTES), fallback: VICTORY_QUOTES.fallback },
  defeat: { outcomes: Object.keys(DEFEAT_QUOTES.personality.grim ?? {}), personality: DEFEAT_QUOTES.personality, class: byClass(DEFEAT_QUOTES), fallback: DEFEAT_QUOTES.fallback },
}
mkdirSync('src/content/generated', { recursive: true })
writeFileSync('src/content/generated/quotes.ts', `// GENERATED by tools/mk-quotes.mjs from hell-tcg/data/combatQuotes.js. Never hand-edit; regenerate.
// The recap's quotes: ${Object.keys(out.victory.class).length} classes with victory lines, ${Object.keys(out.defeat.class).length} with defeat lines; personality pools carried for the day a hero has one.

export type QuoteBank = { readonly outcomes: readonly string[]; readonly personality: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>>; readonly class: Readonly<Record<string, readonly string[]>>; readonly fallback: string }
export const VICTORY_QUOTES: QuoteBank = ${JSON.stringify(out.victory)}
export const DEFEAT_QUOTES: QuoteBank = ${JSON.stringify(out.defeat)}
`)
console.log(`src/content/generated/quotes.ts — victory ${Object.keys(out.victory.class).length} classes, defeat ${Object.keys(out.defeat.class).length}`)
