// The node --test lists that run against the page — ONE list, read by the gate's `--part tests` (tools/gate.mjs) and by
// build-viewer.mjs before it writes BATTLE-VIEWER.html (they were two copies until viewer.play-input, 2026-09-30).
// Each inner list is one `node --test` run with VIEWER_PAGE set to the page under test.
export const PAGE_TESTS = [
  ['tools/equipment-v2.test.mjs'],
  ['tools/transformations.test.mjs'],
  ['tools/terrain-scene.test.mjs', 'tools/terrain-player.test.mjs', 'tools/atlas-combat.test.mjs', 'tools/presentation-review.test.mjs', 'tools/bursts-player.test.mjs', 'tools/clock.test.mjs', 'tools/targeting.test.mjs', 'tools/base-hero-art.test.mjs', 'tools/opportunity-step.test.mjs', 'tools/painted-board.test.mjs', 'tools/character-models.test.mjs', 'tools/bodies-life-size.test.mjs', 'tools/prone-lies-down.test.mjs', 'tools/under-unit.test.mjs', 'tools/play-input.test.mjs', 'tools/play-chrome.test.mjs', 'tools/move-click-setting.test.mjs', 'tools/opening-cast.test.mjs', 'tools/every-model.test.mjs', 'tools/battle-full-screen.test.mjs', 'tools/true-3d-camera.test.mjs', 'tools/bodies-before-board.test.mjs', 'tools/caravan-scene.test.mjs', 'tools/walk-in-step.test.mjs', 'tools/weapons-in-hand.test.mjs', 'tools/xcom-camera.test.mjs', 'tools/view-stays-where-put.test.mjs', 'tools/edge-scroll-at-screen-edges.test.mjs', 'tools/map-drag-and-keys.test.mjs', 'tools/zoom-stays.test.mjs', 'tools/ability-click-keeps-view.test.mjs', 'tools/see-through-only-when-moved.test.mjs', 'tools/scenery-shadow-drawn-once.test.mjs', 'tools/still-frame-draws-nothing.test.mjs', 'tools/solid-pieces-drawn-by-material.test.mjs', 'tools/foliage-drawn-once.test.mjs', 'tools/pixel-agree.test.mjs', 'tools/unit-card-bar.test.mjs', 'tools/characters-unfaded.test.mjs', 'tools/side-facing.test.mjs', 'tools/real-bodies.test.mjs', 'tools/male-hero-outfits.test.mjs', 'tools/swap-bar.test.mjs', 'tools/bar-dblclick.test.mjs', 'tools/shield-guard.test.mjs', 'tools/turn-taking.test.mjs', 'tools/opening-replays.test.mjs', 'tools/opening-scenes.test.mjs'],
  ['tools/direct-map.test.mjs', 'tools/affliction-pop-up.test.mjs', 'tools/bar-follows-activation.test.mjs', 'tools/switch-hero-asks.test.mjs', 'tools/auto-end-no-actions.test.mjs', 'tools/no-hex-focus-border.test.mjs', 'tools/no-target-ring.test.mjs', 'tools/panel-lists-items.test.mjs', 'tools/item-card-in-battle.test.mjs', 'tools/swap-button-rearranges.test.mjs', 'tools/panel-area-trigger-text.test.mjs', 'tools/bar-shows-every-effect.test.mjs', 'tools/friend-line-green-heal-glows.test.mjs', 'tools/log-names-damage-cause.test.mjs', 'tools/unit-names-no-letters-or-numbers.test.mjs', 'tools/bar-shows-tag-requirement.test.mjs', 'tools/bar-moves-grey-when-done.test.mjs', 'tools/prone-turn-only-stand-up.test.mjs', 'tools/unaffordable-actions-greyed.test.mjs', 'tools/bubble-click-reveals.test.mjs', 'tools/tutorial-overlays.test.mjs', 'tools/notices-gold-low-no-backdrop.test.mjs', 'tools/plates-banners-tooltip-gold-look.test.mjs', 'tools/arrivals-camera.test.mjs', 'tools/hex-tooltip.test.mjs', 'tools/move-cost-on-grid.test.mjs', 'tools/move-cost-on-hex.test.mjs', 'tools/fallen-cards-and-first-aid.test.mjs', 'tools/area-fall-warning.test.mjs', 'tools/new-enemy-notice.test.mjs', 'tools/new-enemy-ability-line.test.mjs', 'tools/enemy-type-moves-together.test.mjs', 'tools/camera-shows-edge-units.test.mjs', 'tools/attack-row-shows-totals.test.mjs', 'tools/plates-and-banners-sit-low.test.mjs', 'tools/used-up-power-stays-greyed.test.mjs'],
  ['tools/attack-impact-timing.test.mjs', 'tools/shots-fly-straight.test.mjs', 'tools/hit-slash.test.mjs', 'tools/area-trigger-burst.test.mjs', 'tools/plays-turned-units.test.mjs', 'tools/planted-banner.test.mjs', 'tools/resistance-to-weak.test.mjs','tools/placed-trap.test.mjs', 'tools/stabilised-ally.test.mjs', 'tools/free-attack-kind-words.test.mjs', 'tools/lost-counterattack-line.test.mjs', 'tools/timed-effect-status-marks.test.mjs'],
]
