#!/usr/bin/env python3
"""prep-art.py — the pixel half of the viewer build (THREE-PACKAGES-PLAN stage 1).

Reads the source art (this repo's battle-tokens/, art/, crucible/, assets/, and
the hell-tcg hex-token cutouts on the same machine), downscales and quantizes,
and writes files into generated/art/ plus generated/art/manifest.json — the
ARTMAP the viewer reads (typeId -> token, card, aspect, height). The code half,
tools/build-viewer.mjs, inlines whatever is in generated/art/; it never touches
a source image. Run this only when the art or the map changes.

    python3 tools/prep-art.py [hell-tcg-root] [--only typeId]
    --only refreshes one mapping/token while preserving all unrelated generated bytes.

Remaining stand-ins (bone-dragon for the drake, wolf for the shadow puppy)
are art-thread debts recorded in VFX/VIEWER-CHECKPOINT.md. Where NOTHING honest
exists the token is a generated 'ART PENDING' standee, never borrowed art.
"""
import io, json, os, sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
VIEWER = os.path.dirname(HERE)
ROOT = os.path.dirname(VIEWER)                       # the project root
args = sys.argv[1:]
ONLY = None
if '--only' in args:
    at = args.index('--only')
    if at + 1 >= len(args): raise ValueError('--only requires an exact typeId')
    ONLY = args[at + 1]; del args[at:at + 2]
HELL = args[0] if args else os.path.join(os.path.dirname(ROOT), 'hell-tcg')
OUT = os.path.join(VIEWER, 'generated', 'art')
os.makedirs(OUT, exist_ok=True)
os.chdir(ROOT)

def P(p):
    # sources on the sibling hell-tcg checkout are written as HELL:/... — never a machine path
    return p.replace('HELL:', HELL + '/') if p.startswith('HELL:') else p

ARTMAP = {
 # Complete Eve base roster; existing bodies/cards, warrior stature per VISUAL-BATTLE-UPDATES section 3.3.
 'hero.base.mage-fireaura':{'token': 'mage-fireaura_256.png', 'card': 'card-mage-fireaura', 'src': 'battle-tokens/units/mage-fireaura_256.png', 'cardsrc': 'crucible/art/base/mage-fireaura1.png'},
 'hero.base.mage-sexy':{'token': 'mage-sexy_256.png', 'card': 'card-mage-sexy', 'src': 'battle-tokens/units/mage-sexy_256.png', 'cardsrc': 'crucible/art/base/mage-sexy1.png'},
 'hero.base.mage-thinking':{'token': 'mage-thinking_256.png', 'card': 'card-mage-thinking', 'src': 'battle-tokens/units/mage-thinking_256.png', 'cardsrc': 'crucible/art/base/mage-thinking1.png'},
 'hero.base.paladin-dark':{'token': 'paladin-dark_256.png', 'card': 'card-paladin-dark', 'src': 'battle-tokens/units/paladin-dark_256.png', 'cardsrc': 'crucible/art/base/paladin-dark1.png'},
 'hero.base.paladin-shiney':{'token': 'osric_256.png', 'card': 'card-osric', 'src': 'battle-tokens/units/osric_256.png', 'cardsrc': 'crucible/art/base/paladin-shiney1.png'},
 'hero.base.paladin-smug':{'token': 'paladin-smug_256.png', 'card': 'card-paladin-smug', 'src': 'battle-tokens/units/paladin-smug_256.png', 'cardsrc': 'crucible/art/base/paladin-smug1.png'},
 'hero.base.priest-pauper':{'token': 'priest-pauper_256.png', 'card': 'card-priest-pauper', 'src': 'battle-tokens/units/priest-pauper_256.png', 'cardsrc': 'crucible/art/base/priest-pauper1.png'},
 'hero.base.priest-robes':{'token': 'priest-robes_256.png', 'card': 'card-priest-robes', 'src': 'battle-tokens/units/priest-robes_256.png', 'cardsrc': 'crucible/art/base/priest-robes1.png'},
 'hero.base.priest-scantily':{'token': 'lucius_256.png', 'card': 'card-lucius', 'src': 'battle-tokens/units/lucius_256.png', 'cardsrc': 'crucible/art/base/priest-scantily1.png'},
 'hero.base.ranger-nature':{'token': 'ranger-nature_256.png', 'card': 'card-ranger-nature', 'src': 'battle-tokens/units/ranger-nature_256.png', 'cardsrc': 'crucible/art/base/ranger-nature1.png'},
 'hero.base.ranger-ranger':{'token': 'ranger-ranger_256.png', 'card': 'card-ranger-ranger', 'src': 'battle-tokens/units/ranger-ranger_256.png', 'cardsrc': 'crucible/art/base/ranger-ranger1.png'},
 'hero.base.ranger-scantily':{'token': 'ranger-scantily_256.png', 'card': 'card-ranger-scantily', 'src': 'battle-tokens/units/ranger-scantily_256.png', 'cardsrc': 'crucible/art/base/ranger-scantily1.png'},
 'hero.base.rogue-rose':{'token': 'rogue-rose_256.png', 'card': 'card-rogue-rose', 'src': 'battle-tokens/units/rogue-rose_256.png', 'cardsrc': 'crucible/art/base/rogue-rose1.png'},
 'hero.base.rogue-skull':{'token': 'rogue-skull_256.png', 'card': 'card-rogue-skull', 'src': 'battle-tokens/units/rogue-skull_256.png', 'cardsrc': 'crucible/art/base/rogue-skull1.png'},
 'hero.base.rogue-snake':{'token': 'rogue-snake_256.png', 'card': 'card-rogue-snake', 'src': 'battle-tokens/units/rogue-snake_256.png', 'cardsrc': 'crucible/art/base/rogue-snake1.png'},
 'hero.base.warrior-barbarian':{'token': 'warrior-barbarian_256.png', 'card': 'card-warrior-barbarian', 'src': 'battle-tokens/units/warrior-barbarian_256.png', 'cardsrc': 'crucible/art/base/warrior-barbarian1.png', 'height': 0.95},
 'hero.base.warrior-brawler':{'token': 'warrior-brawler_256.png', 'card': 'card-warrior-brawler', 'src': 'battle-tokens/units/warrior-brawler_256.png', 'cardsrc': 'crucible/art/base/warrior-brawler1.png', 'height': 0.95},
 'hero.base.warrior-fearsome':{'token': 'warrior-fearsome_256.png', 'card': 'card-warrior-fearsome', 'src': 'battle-tokens/units/warrior-fearsome_256.png', 'cardsrc': 'crucible/art/base/warrior-fearsome1.png', 'height': 0.95},
 # Packet fixtures are mechanical deltas of test-oathblade; their authored body is unchanged.
 'test-packet-flame': {'token':'oathblade_256.png','card':'card-oathblade','src':'battle-tokens/units/oathblade_256.png','cardsrc':'crucible/art/avtair/oathblade-v1.png'},
 'test-packet-shadow': {'token':'oathblade_256.png','card':'card-oathblade','src':'battle-tokens/units/oathblade_256.png','cardsrc':'crucible/art/avtair/oathblade-v1.png'},
 'test-oathblade':    {'token':'oathblade_256.png',  'card':'card-oathblade', 'src':'battle-tokens/units/oathblade_256.png',  'cardsrc':'crucible/art/avtair/oathblade-v1.png'},
 'test-sky-pirate':   {'token':'sky-pirate_256.png', 'card':'card-skypirate', 'src':'battle-tokens/units/sky-pirate_256.png', 'cardsrc':'crucible/art/aeronissa/sky-pirate.png'},
 'test-dusk-hawk':    {'token':'dusk-hawk_256.png',  'card':'card-duskhawk',  'src':'battle-tokens/units/dusk-hawk_256.png',  'cardsrc':'crucible/art/avtair/dusk-hawk-v1.png'},
 'test-air-mage':     {'token':'air-mage_256.png',   'card':'card-airmage',   'src':'battle-tokens/units/air-mage_256.png',   'cardsrc':'crucible/art/aeronissa/air-mage.png'},
 'test-lucius':       {'token':'lucius_256.png',     'card':'card-lucius',    'src':'battle-tokens/units/lucius_256.png',     'cardsrc':'crucible/art/base/priest-scantily1.png'},
 'test-osric':        {'token':'osric_256.png',      'card':'card-osric',     'src':'battle-tokens/units/osric_256.png',      'cardsrc':'crucible/art/base/paladin-shiney1.png'},
 'test-zombie':       {'token':'zombie_256.png',     'card':'card-zombie',    'src':'battle-tokens/units/zombie_256.png',     'cardsrc':'assets/bestiary/eve/zombie.png'},
 # The cohort zombie plus a gash rider (engine fixture-migration test); same body.
 'test-gash-zombie': {'token':'zombie_256.png','card':'card-zombie','src':'battle-tokens/units/zombie_256.png','cardsrc':'assets/bestiary/eve/zombie.png'},
 'test-zombie-burning':{'token':'zombie_256.png',    'card':'card-zombie',    'src':'battle-tokens/units/zombie_256.png',     'cardsrc':'assets/bestiary/eve/zombie.png'},
 # ── scenario typeIds (2026-08-27) ─────────────────────────────────────────
 # Tokens from the battle-tokens cutout library where the family matches;
 # bestiary paintings for the panel card. Where NOTHING honest exists the token
 # is a generated 'ART PENDING' standee (ph:), never borrowed wrong art.
 # Exact enemy cutouts are preferred; remaining hero-creature stand-ins
 # are recorded in VIEWER-CHECKPOINT.md for the art thread.
 'hero.base.ranger-aggressive':{'token':'ranger-aggressive_256.png','card':'card-hunter','src':'battle-tokens/units/ranger-aggressive_256.png','cardsrc':'crucible/art/base/ranger-aggressive1.png'},
 'hero.fixed.orphans':          {'token':'orphan-child_256.png','card':'card-orphan','src':'art/heroes/orphan-child/hex/l1_256.png','cardsrc':'art/heroes/orphan-child/card/l1.png','height':1.0},
 'hero.fixed.lumberjack-and-wife':{'token':'lumberjack_256.png','card':'card-lumberjack','src':'art/heroes/lumberjack/hex/l1_256.png','cardsrc':'art/heroes/lumberjack/card/l1.png','height':1.6},
 'hero.fixed.farmer':           {'token':'farmer_256.png','card':'card-farmer','src':'art/heroes/farmer/hex/l1_256.png','cardsrc':'art/heroes/farmer/card/l1.png','height':1.5},
 'unit.skeleton': {'token':'skeleton_256.png','card':'card-skeleton','src':'battle-tokens/units/skeleton_256.png','cardsrc':'assets/bestiary/eve/skeleton.png','height':1.55},
 'unit.zombie':      {'token':'zombie_256.png','card':'card-zombie','src':'battle-tokens/units/zombie_256.png','cardsrc':'assets/bestiary/eve/zombie.png'},
 'unit.fast-zombie': {'token':'fast-zombie_256.png','card':'card-fast-zombie','src':'battle-tokens/units/fast-zombie_256.png','cardsrc':'assets/bestiary/hobat/fast-zombie.png'},
 'unit.skeletal-archer':{'token':'skeletal-archer_256.png','card':'card-skelarcher','src':'battle-tokens/units/skeletal-archer_256.png','cardsrc':'assets/bestiary/eve/skeletal-archer.png'},
 'unit.necromancer': {'token':'necromancer_256.png','card':'card-necro','src':'battle-tokens/units/necromancer_256.png','cardsrc':'assets/bestiary/eve/lesser-necromancer.png'},
 'unit.imp':         {'token':'imp_256.png','card':'card-imp','src':'battle-tokens/units/imp_256.png','cardsrc':'assets/bestiary/eve/imp.png','height':1.2},
 'unit.powerful-imp':{'token':'powerful-imp_256.png','card':'card-powerful-imp','src':'battle-tokens/units/powerful-imp_256.png','cardsrc':'assets/bestiary/hobat/powerful-imp.png','height':1.55},
 'unit.fire-imp':    {'token':'fire-imp_256.png','card':'card-fireimp','src':'battle-tokens/units/fire-imp_256.png','cardsrc':'assets/bestiary/eve/fire-imp.png','height':1.2},
 'unit.poison-imp':  {'token':'poison-imp_256.png','card':'card-poison-imp','src':'battle-tokens/units/poison-imp_256.png','cardsrc':'assets/bestiary/eve/poison-imp.png','height':1.2},
 'unit.bruiser-demon':{'token':'bruiser-demon_256.png','card':'card-bruiser-demon','src':'battle-tokens/units/bruiser-demon_256.png','cardsrc':'assets/bestiary/hobat/bruiser-demon.png','height':2.0},
 'unit.lieutenant-demon':{'token':'lieutenant-demon_256.png','card':'card-lieutenant-demon','src':'battle-tokens/units/lieutenant-demon_256.png','cardsrc':'assets/bestiary/hobat/lieutenant-demon.png','height':2.1},
 'unit.bloodhound':  {'token':'bloodhound_256.png','card':'card-bloodhound','src':'battle-tokens/units/bloodhound_256.png','cardsrc':'assets/bestiary/eve/bloodhound.png','height':1.0},
 'unit.hellhound':   {'token':'hellhound_256.png','card':'card-hellhound','src':'HELL:assets/hex-tokens/hellhound_256.png','cardsrc':'assets/bestiary/eve/hellhound.png','height':1.1},
 'unit.zombie-hound':{'token':'zombie-hound_256.png','card':'card-zombie-hound','src':'battle-tokens/units/zombie-hound_256.png','cardsrc':'assets/bestiary/hobat/zombie-hound.png','height':1.0},
 'unit.werewolf':    {'token':'werewolf_256.png','card':'card-werewolf','src':'battle-tokens/units/werewolf_256.png','cardsrc':'assets/bestiary/eve/werewolf.png','height':1.85},
 'spirit-snake':     {'ph':'Spirit Snake','card':'card-spiritsnake','cardsrc':'HELL:assets/cards/heroes/fixed/spirit-snake/1.png','height':1.0},
 'green-drake':      {'token':'bone-dragon_256.png','card':'card-greendrake','src':'battle-tokens/units/bone-dragon_256.png','cardsrc':'crucible/art/variants/green-drake-level1.png','height':2.1},
 'shadow-hound-puppy':{'token':'wolf_256.png','card':'card-desertwolf','src':'battle-tokens/units/wolf_256.png','cardsrc':'assets/bestiary/shadows/desert-wolf.png','height':0.8},
 # ── engine HEAD 745922d: the S31 ALPHA TEAM and friends (2026-09-01) ───────
 # The alpha cohort is the test cohort rebuilt on real kits — same characters,
 # so the same tokens and cards. arc-golem and the two base heroes had exact
 # cutouts waiting in battle-tokens / hell-tcg hex-tokens.
 'alpha-oathblade': {'token':'oathblade_256.png', 'card':'card-oathblade','src':'battle-tokens/units/oathblade_256.png', 'cardsrc':'crucible/art/avtair/oathblade-v1.png'},
 'alpha-sky-pirate':{'token':'sky-pirate_256.png','card':'card-skypirate','src':'battle-tokens/units/sky-pirate_256.png','cardsrc':'crucible/art/aeronissa/sky-pirate.png'},
 'alpha-dusk-hawk': {'token':'dusk-hawk_256.png', 'card':'card-duskhawk', 'src':'battle-tokens/units/dusk-hawk_256.png', 'cardsrc':'crucible/art/avtair/dusk-hawk-v1.png'},
 'alpha-air-mage':  {'token':'air-mage_256.png',  'card':'card-airmage',  'src':'battle-tokens/units/air-mage_256.png',  'cardsrc':'crucible/art/aeronissa/air-mage.png'},
 'alpha-lucius':    {'token':'lucius_256.png',    'card':'card-lucius',   'src':'battle-tokens/units/lucius_256.png',    'cardsrc':'crucible/art/base/priest-scantily1.png'},
 'alpha-osric':     {'token':'osric_256.png',     'card':'card-osric',    'src':'battle-tokens/units/osric_256.png',     'cardsrc':'crucible/art/base/paladin-shiney1.png'},
 'arc-golem':       {'token':'stone-golem_256.png','card':'card-golem',   'src':'HELL:assets/hex-tokens/stone-golem_256.png','cardsrc':'assets/bestiary/eve/stone-golem.png','height':2.0},
 'hero.base.priest-armored':{'token':'priest-armored_256.png','card':'card-priestarm','src':'battle-tokens/units/priest-armored_256.png','cardsrc':'crucible/art/base/priest-armored1.png'},
 # the Eve warriors are DWARFS (Angela 2026-09-03: "scaled to the same height as humans, they look massive") — the
 # stature ladder's child rung (0.60 of a human, create-battle-token skill): artmap 0.95 against the human 1.55
 'hero.base.warrior-iron':  {'token':'warrior-iron_256.png',  'card':'card-warriron', 'src':'battle-tokens/units/warrior-iron_256.png',  'cardsrc':'crucible/art/base/warrior-iron1.png','height':0.95},
 # ── the encounters (2026-09-03): Supper, The Kiln, Horrors of the Night ────
 # Exact cutouts from battle-tokens/ and the hobat bestiary paintings for the
 # cards. The Supper villagers have no hex art at all — honest standees, never
 # a borrowed farmer (Law 1).
 'hero.base.mage-fire':    {'token':'mage-fire_256.png',    'card':'card-magefire',   'src':'battle-tokens/units/mage-fire_256.png',    'cardsrc':'crucible/art/base/mage-fire1.png'},
 'hero.base.paladin-hunk': {'token':'paladin-hunk_256.png', 'card':'card-palhunk',    'src':'battle-tokens/units/paladin-hunk_256.png', 'cardsrc':'crucible/art/base/paladin-hunk1.png'},
 'hero.base.rogue-raven':  {'token':'rogue-raven_256.png',  'card':'card-rogueraven', 'src':'battle-tokens/units/rogue-raven_256.png',  'cardsrc':'crucible/art/base/rogue-raven1.jpg'},
 'unit.ghoul':             {'token':'ghoul_256.png',           'card':'card-ghoul',      'src':'battle-tokens/units/ghoul_256.png',           'cardsrc':'assets/bestiary/hobat/ghoul.png'},
 'unit.dark-sniper':       {'token':'dark-sniper_256.png',     'card':'card-darksniper', 'src':'battle-tokens/units/dark-sniper_256.png',     'cardsrc':'assets/bestiary/hobat/dark-sniper.png'},
 'unit.nightstalker':      {'token':'nightstalker_256.png',    'card':'card-nightstalker','src':'battle-tokens/units/nightstalker_256.png',   'cardsrc':'assets/bestiary/hobat/nightstalker.png','height':1.7},
 'unit.shadow-sorcerer':   {'token':'shadow-sorcerer_256.png', 'card':'card-shadowsorc', 'src':'battle-tokens/units/shadow-sorcerer_256.png', 'cardsrc':'assets/bestiary/hobat/shadow-sorcerer.png'},
 'unit.eyeblight':         {'token':'eyeblight_256.png',       'card':'card-eyeblight',  'src':'battle-tokens/units/eyeblight_256.png',       'cardsrc':'assets/bestiary/hobat/eyeblight.png','height':1.2},
 'unit.imp-master':        {'token':'imp-master_256.png',      'card':'card-impmaster',  'src':'battle-tokens/units/imp-master_256.png',      'cardsrc':'assets/bestiary/hobat/imp-master.png','height':1.7},
 'unit.balrog':            {'token':'balrog_256.png',          'card':'card-balrog',     'src':'battle-tokens/units/balrog_256.png',          'cardsrc':'assets/bestiary/hobat/balrog.png','height':2.4},
 'unit.strong-skeleton':   {'token':'strong-skeleton_256.png', 'card':'card-strongskel', 'src':'battle-tokens/units/strong-skeleton_256.png', 'cardsrc':'assets/bestiary/hobat/strong-skeleton.png'},
 'unit.skeleton-spider':   {'token':'skeleton-spider_256.png', 'card':'card-skelspider', 'src':'battle-tokens/units/skeleton-spider_256.png', 'cardsrc':'assets/bestiary/hobat/skeleton-spider.png','height':1.1},
 'unit.bone-dragon':       {'token':'bone-dragon_256.png',     'card':'card-bonedragon', 'src':'battle-tokens/units/bone-dragon_256.png',     'cardsrc':'assets/bestiary/eve/bone-dragon.png','height':2.3},
 'hero.fixed.librarian':        {'ph':'Librarian',        'height':1.5},
 'hero.fixed.cook':             {'ph':'Cook',             'height':1.5},
 'hero.fixed.fishermans-wife':  {'ph':'Fishermans Wife',  'height':1.5},
 'hero.fixed.fisherman':        {'ph':'Fisherman',        'height':1.5},
 'hero.fixed.old-wise-man':     {'ph':'Old Wise Man',     'height':1.4},
 'hero.fixed.blacksmith':       {'ph':'Blacksmith',       'height':1.6},
 'hero.fixed.group-of-farmers': {'ph':'Group Farmers',    'height':1.6},
 'hero.fixed.farming-family':   {'ph':'Farming Family',   'height':1.6},
 'hero.fixed.scary-kid':        {'ph':'Scary Kid',        'height':1.0},
 # engine 4516bbb renamed two probe bodies: the arc golem is `test-arc-golem`, the burning zombie `unit.zombie-burning`
 'test-arc-golem':      {'token':'stone-golem_256.png','card':'card-golem',   'src':'HELL:assets/hex-tokens/stone-golem_256.png','cardsrc':'assets/bestiary/eve/stone-golem.png','height':2.0},
 'unit.zombie-burning': {'token':'zombie_256.png','card':'card-zombie','src':'battle-tokens/units/zombie_256.png','cardsrc':'assets/bestiary/eve/zombie.png'},
}

def placeholder_token(label):
    W, H = 256, 400
    im = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    d.ellipse([48, 352, 208, 396], fill=(20, 18, 14, 140))            # base shadow
    d.rounded_rectangle([78, 120, 178, 370], 34, fill=(58, 54, 46, 235),
                        outline=(122, 112, 92, 255), width=4)          # body
    d.ellipse([92, 44, 164, 116], fill=(58, 54, 46, 235),
              outline=(122, 112, 92, 255), width=4)                    # head
    try:
        f1 = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 56)
        f2 = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 22)
    except OSError:
        f1 = f2 = ImageFont.load_default()
    init = ''.join(w[0] for w in label.split()[:2]).upper()
    d.text((128, 210), init, font=f1, fill=(232, 222, 190, 255), anchor='mm')
    d.text((128, 300), 'ART', font=f2, fill=(180, 168, 140, 255), anchor='mm')
    d.text((128, 326), 'PENDING', font=f2, fill=(180, 168, 140, 255), anchor='mm')
    return im

if ONLY and ONLY not in ARTMAP: raise ValueError('Unknown art typeId: ' + ONLY)
previous = json.load(open(os.path.join(OUT, 'manifest.json'))) if ONLY else None
written = dict.fromkeys(previous['files'], True) if ONLY else {}
from art_reuse import shared_files_for_new_mapping
reused = shared_files_for_new_mapping(ONLY, previous, ARTMAP) if ONLY else set()
def save_png(name, im):
    if name in reused or (name in written and not ONLY): return
    if im.mode == 'RGBA': im = im.quantize(256)   # flat-shaded art loses nothing visible, file drops ~60%
    im.save(os.path.join(OUT, name), 'PNG', optimize=True); written[name] = True
def save_jpg(name, im):
    if name in reused or (name in written and not ONLY): return
    im.save(os.path.join(OUT, name), 'JPEG', quality=82, optimize=True); written[name] = True

manifest = previous['artmap'] if ONLY else {}
for tid, m in ARTMAP.items():
    if ONLY and tid != ONLY: continue
    if 'ph' in m:
        token = 'ph-' + m['ph'].lower().replace(' ', '-') + '.png'
        im = placeholder_token(m['ph'])
    else:
        token = m['token']
        src = P(m['src'])
        if token in reused:
            # Bind the existing published shared file; this is not a source refresh.
            im = Image.open(os.path.join(OUT, token))
        elif not os.path.exists(src) and m['src'].startswith('HELL:') and os.path.exists(os.path.join(OUT, token)):
            # the hell-tcg checkout is not on this machine (a sandbox): keep the
            # token this tool wrote from it last time, and say so — never a
            # silent substitute (2026-09-03)
            print('prep-art: %s — source %s not mounted; keeping the existing generated/art/%s' % (tid, m['src'], token), file=sys.stderr)
            im = Image.open(os.path.join(OUT, token)); written[token] = True
        else:
            im = Image.open(src)
    save_png(token, im.convert('RGBA'))
    card = m.get('card')
    if card:
        csrc = P(m['cardsrc'])
        if card + '.jpg' in reused:
            if not os.path.isfile(os.path.join(OUT, card + '.jpg')): raise ValueError('missing shared card: ' + card)
        elif not os.path.exists(csrc) and m['cardsrc'].startswith('HELL:') and os.path.exists(os.path.join(OUT, card + '.jpg')):
            print('prep-art: %s — card source %s not mounted; keeping the existing generated/art/%s.jpg' % (tid, m['cardsrc'], card), file=sys.stderr)
            written[card + '.jpg'] = True
        else:
            cim = Image.open(csrc).convert('RGB'); cim.thumbnail((496, 744), Image.LANCZOS)
            save_jpg(card + '.jpg', cim)
    manifest[tid] = {'token': token, 'card': (card + '.jpg') if card else None,
                     'aspect': round(im.width / im.height, 4), 'height': m.get('height', 1.55)}
if not ONLY:
    # the honest standee for a typeId with no art entry at all — Law 1: never borrowed art
    save_png('ph-art-pending.png', placeholder_token('Art Pending'))
    manifest['_pending'] = {'token': 'ph-art-pending.png', 'card': None, 'aspect': round(256 / 400, 4), 'height': 1.55}
    # the parchment surround: a hand-placed SOURCE in art-src/, copied here so generated/ is whole
    import shutil
    shutil.copyfile(os.path.join(VIEWER, 'art-src', 'parchment.jpg'), os.path.join(OUT, 'parchment.jpg')); written['parchment.jpg'] = True
    # swatches stay PNG — their transparent corners went black as JPEG
    for sw in ['hexPlains','hexForest','hexHills','hexScrub','hexOcean','hexMountain','hexDirt','hexMarsh']:
        save_png(sw + '.png', Image.open('VFX/battle-screen-mocks/art/%s.png' % sw).convert('RGBA'))
# clear anything this run did not write — a stale token must not ship forever
for f in ([] if ONLY else os.listdir(OUT)):
    if f != 'manifest.json' and f not in written:
        os.remove(os.path.join(OUT, f))
json.dump({'_about': 'Generated by tools/prep-art.py — never hand-edit. typeId -> token/card file in this folder, aspect, height. _pending is the ART PENDING standee for any typeId with no entry.',
           'files': sorted(written), 'artmap': manifest}, open(os.path.join(OUT, 'manifest.json'), 'w'), indent=1)
print('prep-art: %d typeIds · %d files -> generated/art/' % (len(manifest), len(written)))
